// Diccionario de textos de Nospi en español e ingles.
//
// Reglas al agregar textos:
//   - La clave se nombra pantalla.loQueEs  (ej: 'login.entrar')
//   - Si falta la traduccion en ingles, la app muestra el español. No se rompe.
//   - Las variables van como {{nombre}} y se pasan en el segundo argumento:
//       t('detalle.disponibleALas', { hora: '7:00 PM' })
//   - El ingles NO es traduccion literal: esta escrito como lo diria un gringo.

import type { Idioma } from '@/lib/i18n';

export const TEXTOS: Record<Idioma, Record<string, string>> = {
  es: {
    // ---------- Comunes ----------
    'comun.atras': 'Atrás',
    'comun.cancelar': 'Cancelar',
    'comun.aceptar': 'Aceptar',
    'comun.continuar': 'Continuar',
    'comun.cerrar': 'Cerrar',
    'comun.error': 'Error',
    'comun.errorInesperado': 'Ocurrió un error inesperado. Por favor, intenta de nuevo.',
    'comun.cargando': 'Cargando...',
    'comun.reintentar': 'Reintentar',
    'comun.faltaUnPaso': 'Falta un paso',

    // ---------- Tipos de evento ----------
    'evento.tipo.bar': 'Bar',
    'evento.tipo.caminata': 'Caminata',
    'evento.tipo.cafe': 'Café',
    'evento.tipo.bolos': 'Bolos',
    'evento.tipo.virtual': 'Videollamada',
    'evento.tipo.restaurante': 'Restaurante',

    // ---------- Login ----------
    'login.subtituloEntrar': 'Inicia sesión para continuar',
    'login.subtituloCrear': 'Únete a Nospi',
    'login.botonEntrar': 'Iniciar sesión',
    'login.botonCrear': 'Crear cuenta',
    'login.cambiarAEntrar': '¿Ya tienes cuenta? Inicia sesión',
    'login.cambiarACrear': '¿No tienes cuenta? Regístrate',
    'login.contrasena': 'Contraseña',
    'login.olvidasteContrasena': '¿Olvidaste tu contraseña?',
    'login.faltaEmailOContrasena': 'Por favor ingresa tu email y contraseña',
    'login.credencialesMalas': 'Email o contraseña incorrectos',
    'login.errorEntrar': 'Error al iniciar sesión',
    'login.errorEntrarReintenta': 'Error al iniciar sesión. Intenta de nuevo.',
    'login.errorCrearReintenta': 'Error al crear cuenta. Intenta de nuevo.',
    'login.cuentaNoExiste': 'No encontramos una cuenta registrada con este método. Por favor regístrate primero.',
    'login.cuentaYaExiste': 'Esta cuenta ya está registrada. Inicia sesión directamente.',
    'login.contrasenaInvalida': 'Esa contraseña no es válida. Usa al menos 8 caracteres.',
    'login.contrasenaCorta': 'Tu contraseña es muy corta. Usa al menos 8 caracteres.',
    'login.cuentaEsDeGoogle': 'Esta cuenta la creaste con Google. Toca "Continuar con Google" (arriba) para entrar — no necesitas contraseña.',
    'login.cuentaEsDeApple': 'Esta cuenta la creaste con Apple. Toca "Continuar con Apple" (arriba) para entrar — no necesitas contraseña.',
    'login.canceladoApple': 'Inicio de sesión cancelado',
    'login.errorApple': 'Error al iniciar sesión con Apple',
    'login.errorGoogle': 'Error al iniciar sesión con Google',

    // ---------- Recuperar contraseña ----------
    'recuperar.titulo': '¿Olvidaste tu contraseña?',
    'recuperar.volverAEntrar': 'Volver a iniciar sesión',

    // ---------- Lista de eventos ----------
    'eventos.estaSemana': 'Esta semana',
    'eventos.proximaSemana': 'La próxima semana',
    'eventos.enDosSemanas': 'En 2 semanas',
    'eventos.masAdelante': 'Más adelante',
    'eventos.sinFecha': 'Fecha sin definir',
    'eventos.cambiarCiudad': '¿No es tu ciudad? Cámbiala en tu perfil',
    'eventos.elegirCiudad': 'Elige tu ciudad en tu perfil',
    'eventos.ubicacionUnDiaAntes': 'Ubicación se revelará un día antes',

    // ---------- Detalle del evento ----------
    'detalle.titulo': 'Detalles del Evento',
    'detalle.deseasAsistir': '¿Deseas asistir?',
    'detalle.videollamada': '🎥 Videollamada',
    'detalle.ubicacion': '📍 Ubicación',
    'detalle.irALaDinamica': 'Ir a la Dinámica',
    'detalle.yaEstasInscrito': '✓ Ya estás inscrito',
    'detalle.reservado': '✦ ¡RESERVADO! ✦',
    'detalle.cupoAsegurado': 'Tu cupo está asegurado 🎉',
    'detalle.ubicacionLaEnviamos': 'Te enviaremos la ubicación un día antes',
    'detalle.disponibleALas': 'Disponible a las {{hora}}',
    'detalle.disponibleElDia': 'Disponible el día del evento',
    'detalle.verPoliticaCompleta': 'Ver política completa',
    'detalle.aceptoBolos': 'Leí que la pista y los zapatos se pagan aparte, directamente en la bolera.',
    'detalle.aceptoGeneral': 'Leí la información anterior y acepto participar bajo mi propia responsabilidad.',

    'detalle.confirmarAsistencia': 'Confirmar Asistencia',
    'detalle.gratis': 'Gratis',
    'detalle.marcaCasillaBolos': 'Para reservar primero marca la casilla de arriba confirmando que leíste que la pista y los zapatos se pagan aparte en la bolera.',
    'detalle.marcaCasillaGeneral': 'Para reservar primero marca la casilla de arriba aceptando participar bajo tu propia responsabilidad.',

    // ---------- Mis citas ----------
    'citas.elegirConQuienConecte': '💘 Elegir con quién conecté',
    'citas.ubicacionUnDiaAntes': 'Ubicación se revelará un día antes del evento',
    'citas.cancelarCita': '¿Cancelar Cita?',
    'citas.siCancelar': 'Sí, cancelar',

    // ---------- Pago ----------
    'pago.verificandoSuscripcion': 'Verificando tu suscripción...',
    'pago.suscripcionActivada': '¡Suscripción activada!',
    'pago.enVerificacion': 'Tu pago sigue en verificación. Te confirmaremos apenas se complete.',
    'pago.errorVerificando': 'Error verificando tu suscripción.',
    'pago.transaccionNoEncontrada': 'No se encontró la transacción.',
    'pago.expiro': 'El pago expiró.',
    'pago.aprobado': '¡Pago aprobado! Confirmando asistencia...',
    'pago.seProcesaAutomaticamente': 'Tu pago se procesará automáticamente',

    // ---------- Títulos del onboarding ----------
    'onboarding.gustos': 'Tus Gustos',
    'onboarding.nombre': 'Tu Nombre',
    'onboarding.fechaNacimiento': 'Fecha de Nacimiento',
    'onboarding.genero': 'Tu Género',
    'onboarding.intereses': 'Intereses',
    'onboarding.edades': 'Edades',
    'onboarding.ubicacion': 'Ubicación',
    'onboarding.compatibilidad': 'Compatibilidad',
    'onboarding.telefono': 'Teléfono',
    'onboarding.foto': 'Foto de Perfil',
    'onboarding.registro': 'Registro',

    // ---------- Idioma de la mesa ----------
    'mesaIdioma.pregunta': '¿En qué idiomas estás dispuesto a hablar en la mesa?',
    'mesaIdioma.preguntaSala': '¿En qué idiomas estás dispuesto a hablar en la sala?',
    'mesaIdioma.explicacion': 'Te sentamos con gente que escogió lo mismo. Puedes marcar los dos.',
    'mesaIdioma.explicacionSala': 'Te ponemos en una sala con gente que escogió lo mismo. Puedes marcar los dos.',
    'mesaIdioma.espanol': 'Español',
    'mesaIdioma.ingles': 'Inglés',
    'mesaIdioma.inglesSub': 'Con gente de afuera',
    'mesaIdioma.tuCupo': 'Tu cupo',
    'mesaIdioma.escogeUno': 'Escoge al menos un idioma para continuar.',

    // ---------- Zona preferida ----------
    'zona.pregunta': '¿En qué zona te gustaría?',
    'zona.explicacion': 'Marca todas las que te sirvan.',
    'zona.aviso': 'Esto no define dónde será el evento. Nos sirve para saber a qué zonas abrir más adelante.',
    'zona.poblado': 'El Poblado',
    'zona.pobladoSub': 'La mayoría de las cenas',
    'zona.laureles': 'Laureles',
    'zona.laurelesSub': 'Cafés y bolos',
    'zona.envigado': 'Envigado',
    'zona.otra': 'Otra',
    'zona.otraSub': 'Dinos cuál',
    'zona.otraPlaceholder': '¿Cuál? Escríbela',
    'zona.escribeCual': 'Escribe cuál es esa zona para poder continuar.',

    'eventos.titulo': 'Eventos Disponibles',
    'eventos.enCiudad': 'Eventos en {{ciudad}}',
    'eventos.todasLasCiudades': 'Eventos de todas las ciudades',
    'eventos.gratis': 'GRATIS',
    'eventos.camaraPrendidaEnlaceYa': 'Con cámara prendida · enlace ya disponible',
    'eventos.camaraPrendidaEnlaceDespues': 'Con cámara prendida · enlace el mismo día',
    'eventos.diasCortos': 'Dom,Lun,Mar,Mié,Jue,Vie,Sáb',
    'eventos.mesesCortos': 'ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic',

    // ---------- Bienvenida ----------
    'bienvenida.tagline1': 'Tu dosis semanal',
    'bienvenida.tagline2': 'de conexión',
    'bienvenida.subtitulo': 'Conoce personas reales en encuentros grupales cada semana',
    'bienvenida.empezar': 'Empezar',
    'bienvenida.yaTengoCuenta': 'Ya tengo una cuenta',

    // ---------- Suscripción ----------
    'sus.titulo': 'Suscripción mensual Nospi',
    'sus.activa': 'Tu suscripción está activa',
    'sus.seRenueva': 'Se renueva automáticamente cada mes',
    'sus.noSeRenueva': 'No se renovará — termina en la fecha indicada',
    'sus.metodoPago': 'Método de pago',
    'sus.cancelarRenovacion': 'Cancelar renovación automática',
    'sus.reactivarRenovacion': 'Reactivar renovación automática',
    'sus.recomendado': 'Recomendado',
    'sus.masElegido': 'MÁS ELEGIDO',
    'sus.descripcion': 'Eventos ilimitados, todos los que hagamos. Escoge por cuánto tiempo.',
    'sus.plan1': '1 mes',
    'sus.plan3': '3 meses',
    'sus.plan6': '6 meses',
    'sus.alMes': '{{precio}} al mes',
    'sus.ahorras': 'Ahorras {{monto}}',
    'sus.feature1': 'Acceso sin límite a todos los eventos del mes',
    'sus.feature2': 'Sin pagar cada evento por separado',
    'sus.feature3': 'Cancela cuando quieras',
    'sus.breakEven': 'Te conviene si vas a {{n}}+ eventos al mes',
    'sus.suscribirme': 'Suscribirme',
    'sus.porQueCancelas': '¿Por qué cancelas?',
    'sus.cancelarSuscripcion': 'Cancelar suscripción',
    'sus.activada': '¡Suscripción activada!',
    'sus.cancelada': 'Suscripción cancelada',
    'sus.canceladaSub': 'Dejarás de renovar automáticamente. Conservas el acceso hasta el final del período ya pagado.',
    'sus.reactivada': '¡Renovación reactivada!',
    'sus.reactivadaSub': 'Tu suscripción volverá a renovarse automáticamente cada mes con la tarjeta que ya tenías registrada.',
    'sus.nombreTitular': 'Nombre del titular',

    // ---------- Perfil ----------
    'perfil.infoPersonal': 'Información Personal',
    'perfil.gustos': 'Gustos',
    'perfil.intereses': 'Intereses',
    'perfil.personalidad': 'Personalidad',
    'perfil.notificaciones': 'Preferencias de Notificaciones',
    'perfil.notificacionesSub': 'Toca para configurar',
    'perfil.contrasena': 'Cambiar Contraseña',
    'perfil.contrasenaSub': 'Actualiza tu contraseña',
    'perfil.suscripcion': 'Suscripción mensual Nospi',
    'perfil.suscripcionSub': 'Acceso ilimitado a todos los eventos del mes',
    'perfil.politica': 'Política de asistencia',
    'perfil.politicaSub': 'Cancelación, saldo y suspensiones',
    'perfil.soporte': 'Soporte',
    'perfil.soporteSub': '¿Necesitas ayuda? Contáctanos',

    'perfil.misFotos': 'Mis fotos · {{n}} de 6',
    'perfil.misFotosVacio': 'Agrega tus fotos',
    'perfil.misFotosA11y': 'Mis fotos, {{n}} de 6',
    'perfil.editarPerfil': 'Editar perfil',
    'perfil.editarPerfilTitulo': 'Editar Perfil',
    'perfil.telefono': 'Teléfono',
    'perfil.genero': 'Género',
    'perfil.ubicacion': 'Ubicación',
    'perfil.rangoEdad': 'Rango de edad preferido',
    'perfil.sinIntereses': 'No has agregado intereses aún',
    'perfil.sinRasgos': 'No has agregado rasgos de personalidad aún',
    'perfil.sobreMi': 'Sobre mí',
    'perfil.sobreMiEjemplo': 'Ej: Me río de todo, cocino mejor de lo que bailo y siempre digo que sí a un café.',
    'perfil.tuTelefono': 'Tu teléfono',
    'perfil.pais': 'País',
    'perfil.seleccionaPais': 'Selecciona tu país',
    'perfil.buscarPais': 'Buscar país o código...',
    'perfil.minimo': 'Mínimo',
    'perfil.maximo': 'Máximo',
    'perfil.guardarCambios': 'Guardar Cambios',
    'perfil.eliminarCuenta': 'Eliminar Cuenta',
    'perfil.cerrarSesion': 'Cerrar Sesión',
    'perfil.correoSub': 'Envíanos un mensaje',
    'perfil.whatsappSub': 'Chatea con nosotros',
    'perfil.tuCorreo': 'Tu correo electrónico',
    'perfil.mensajeEnviado': '¡Mensaje enviado!',
    'perfil.notifSubtitulo': 'Elige qué quieres que te llegue',
    'perfil.sesionCerrada': 'Tu sesión se cerró. Inicia sesión de nuevo para ver tu perfil y confirmar tu asistencia.',
    'perfil.sesionCerradaHint': 'Estás viendo Nospi dentro de otra app (por ejemplo WhatsApp). Ábrelo en Safari, Chrome o en la app de Nospi para poder iniciar sesión.',
    'perfil.contrasenaSubtitulo': 'Ingresa tu contraseña actual y la nueva',
    'perfil.contrasenaActual': 'Contraseña Actual *',
    'perfil.contrasenaActualPh': 'Contraseña actual',
    'perfil.contrasenaNueva': 'Nueva Contraseña *',
    'perfil.contrasenaNuevaPh': 'Nueva contraseña (mínimo 6 caracteres)',
    'perfil.contrasenaConfirmar': 'Confirmar Nueva Contraseña *',
    'perfil.contrasenaConfirmarPh': 'Confirma la nueva contraseña',

    // ---------- Notificaciones ----------
    'notif.privadosTitulo': 'Mensajes privados',
    'notif.privadosAyuda': 'Cuando alguien te escribe directo',
    'notif.novedadesTitulo': 'Novedades y nuevos eventos',
    'notif.novedadesAyuda': 'Eventos nuevos, cupos libres y avisos de Nospi',
    'notif.promocionesTitulo': 'Promociones y descuentos',
    'notif.promocionesAyuda': 'Ofertas y campañas',
    'notif.mesaTitulo': 'El chat de mi mesa',
    'notif.mesaAyuda': 'El grupo de las personas de tu evento',
    'notif.comunidadTitulo': 'Comunidad Nospi',
    'notif.comunidadAyuda': 'El grupo grande, con todos',
    'notif.modoTodos': 'Todos',
    'notif.modoMenciones': 'Solo si me mencionan',
    'notif.modoNinguno': 'Ninguno',
    'notif.siempreLlegan': 'Los avisos de tus reservas —la hora, el lugar, cambios de mesa y lo que se publique en el canal de tu evento— llegan siempre.',

    // ---------- Privacidad ----------
    'priv.titulo': 'Privacidad',
    'priv.subtitulo': 'Quién ve cuándo estás conectado',
    'priv.enLineaTitulo': 'Cuando estoy en línea',
    'priv.enLineaAyuda': 'Los demás ven un punto verde cuando tienes la app abierta.',
    'priv.ultimaVezTitulo': 'Mi última vez',
    'priv.ultimaVezAyuda': 'Ven cuándo fue la última vez que estuviste. Por ejemplo: «hoy a las 3:40 p. m.».',

    'priv.reciprocidad': 'Esto decide qué ven los demás de ti. Si apagas algo, tú tampoco lo ves de ellos.',
    'priv.resumenTodoApagado': 'Nadie sabe cuándo te conectas. Tú tampoco lo ves de nadie.',
    'priv.resumenSinUltimaVez': 'Nadie ve tu última vez —y tú tampoco la de los demás—, pero el punto verde sigue funcionando en los dos sentidos.',
    'priv.resumenTodoEncendido': 'Ves el punto verde y la última vez de todos los que también lo tengan encendido.',
    'priv.ultimaVezAhora': 'última vez hace un momento',
    'priv.ultimaVezMinutos': 'última vez hace {{n}} {{unidad}}',
    'priv.minuto': 'minuto',
    'priv.minutos': 'minutos',
    'priv.ultimaVezHoy': 'última vez hoy a las {{hora}}',
    'priv.ultimaVezAyer': 'última vez ayer a las {{hora}}',
    'priv.ultimaVezDia': 'última vez el {{dia}} a las {{hora}}',
    'priv.ultimaVezFecha': 'última vez el {{dia}} de {{mes}}',
    'priv.dias': 'domingo,lunes,martes,miércoles,jueves,viernes,sábado',
    'priv.meses': 'enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre',
    'priv.am': 'a. m.',
    'priv.pm': 'p. m.',

    'perfil.nombre': 'Nombre',
    'perfil.ciudad': 'Ciudad',
    'perfil.rangoEdadEtiqueta': 'Edades con las que te sientes cómodo',
    'perfil.rangoEdadAyuda': 'Lo usamos para armar tu mesa: entre más amplio, más probable que quedes con gente afín.',
    'perfil.eliminarPregunta': '¿Estás seguro de que deseas eliminar tu cuenta?',
    'perfil.eliminando': 'Eliminando...',
    'perfil.siEliminar': 'Sí, eliminar mi cuenta',
    'perfil.sinInfoUsuario': 'No se encontró información de usuario',
    'perfil.celularRepetido': 'Este número de celular ya está registrado por otro usuario. Por favor usa un número diferente.',
    'perfil.contrasenaCorta6': 'La nueva contraseña debe tener al menos 6 caracteres',
    'perfil.contrasenasNoCoinciden': 'Las contraseñas no coinciden',
    'perfil.contrasenaActualMala': 'La contraseña actual es incorrecta',

    // ---------- Política de asistencia ----------
    'pol.titulo': 'Política de asistencia',
    'pol.lead': 'Cuidamos que cada mesa esté completa para que la experiencia sea buena para todas',
    'pol.leadB': 'Por eso te pedimos avisar a tiempo si no puedes ir.',
    'pol.cancelTitulo': '🗓️  Cancelación',
    'pol.cancel1a': 'Si no vas a poder asistir, puedes ',
    'pol.cancel1b': 'cancelar desde la app con más de 24 horas',
    'pol.cancel1c': ' de anticipación y te devolvemos tu ',
    'pol.cancel1d': 'saldo',
    'pol.cancel1e': ' para que lo uses en otro evento, sin ninguna consecuencia.',
    'pol.cancel2a': 'Si cancelas con ',
    'pol.cancel2b': 'menos de 24 horas',
    'pol.cancel2c': ' o si ',
    'pol.cancel2d': 'no asistes',
    'pol.cancel2e': ', no alcanzamos a devolverte el saldo y queda ',
    'pol.cancel2f': 'una falta',
    'pol.cancel2g': ' en tu cuenta: a esa hora tu cupo ya está reservado y el grupo armado.',
    'pol.faltasTitulo': 'Cómo se cuentan las faltas',
    'pol.nivel1': 'Aviso',
    'pol.nivel1Desc': 'Primera falta: solo te avisamos, sin bloqueo.',
    'pol.nivel2': 'Suspensión 15 días',
    'pol.nivel2Desc': 'Segunda falta: no puedes reservar durante 15 días.',
    'pol.nivel3': 'Suspensión 60 días',
    'pol.nivel3Desc': 'Tercera falta: no puedes reservar durante 60 días.',
    'pol.nota': 'Las faltas se borran a los ~4 meses de buen comportamiento.',
    'pol.suspTitulo': '🔓  ¿Qué es la suspensión?',
    'pol.susp1a': 'Solo significa que ',
    'pol.susp1b': 'no puedes reservar',
    'pol.susp1c': ' nuevos eventos por ese tiempo. Sigues usando la app con normalidad (chat, perfil…).',
    'pol.soporteTitulo': '🛟  ¿Tuviste un problema?',
    'pol.soporte1a': 'Si algo falló al confirmar tu asistencia o al entrar, ',
    'pol.soporte1b': 'escríbenos a soporte',
    'pol.soporte1c': ' y lo solucionamos. Nunca suspendemos por un fallo técnico ni por avisar a tiempo.',

    // ---------- Pago de un evento ----------
    'pag.confirmaAsistencia': 'Confirma tu asistencia',
    'pag.porEvento': 'Por evento',
    'pag.porEventoUnidad': '/ evento',
    'pag.porEventoSub': 'Pagas cada vez que vengas a un evento.',
    'pag.porMes': '/ mes',
    'pag.susSub': 'Eventos ilimitados, todos los que hagamos este mes.',
    'pag.desdeAlMes': 'o desde {{precio}} al mes con los planes de 3 y 6 meses',
    'pag.tienesCodigo': '¿Tienes un código promocional?',
    'pag.codigoLabel': 'Código promocional',
    'pag.codigoPlaceholder': 'Ingresa tu código',
    'pag.codigoAplicado': 'Código aplicado',
    'pag.codigoGratis': 'Tu inscripción a este evento queda gratis.',
    'pag.codigoDescuento': 'Se descontará del total al elegir tu método de pago.',
    'pag.comoPagar': '¿Cómo quieres pagar?',
    'pag.tarjetaCredito': 'Tarjeta de Crédito',
    'pag.numeroTarjeta': 'Número de tarjeta',
    'pag.pagarMonto': 'Pagar {{monto}}',
    'pag.nequiDesc': 'Ingresa tu número de celular registrado en Nequi. Recibirás una notificación push para aprobar el pago.',
    'pag.celularNequi': 'Número de celular Nequi',
    'pag.esperando': 'Esperando confirmación...',
    'pag.apruebaNequi': 'Aprueba el pago de',
    'pag.apruebaNequiFin': 'desde tu app Nequi.',
    'pag.numeroDocumento': 'Número de documento',
    'pag.pagoExitoso': '¡Pago Exitoso!',
    'pag.cupoConfirmado': '¡Cupo confirmado!',
    'pag.cupoGratis': '¡Cupo confirmado gratis!',
    'pag.cupoGratisSub': 'Tu código promocional cubrió este evento — ya tienes tu lugar asegurado',
    'pag.codigoAplicadoTitulo': '¡Código aplicado!',
    'pag.verPolitica': 'Ver política de asistencia',
    'pag.politicaLarga': 'Si no vas a poder asistir, puedes cancelar desde la app con más de 24 horas de anticipación y te devolvemos tu saldo para que lo uses en otro evento. Si lo haces con menos de 24 horas o no asistes, no alcanzamos a devolverte el saldo y tu cuenta podría quedar suspendida para reservar por un tiempo.',
    'pag.politicaCorta': 'Si no vas a poder asistir, puedes cancelar desde la app con más de 24 horas de anticipación, sin problema. Si lo haces con menos de 24 horas o no asistes, tu cuenta podría quedar suspendida para reservar por un tiempo.',

    // ---------- Mis fotos ----------
    'fotos.titulo': 'Mis fotos',
    'fotos.ayuda': 'Puedes subir hasta {{max}}. La primera es tu foto de perfil, y las demás las ven las personas de tu grupo antes del evento.',
    'fotos.listo': 'Listo',
    'fotos.principal': 'PRINCIPAL',
    'fotos.hacerPrincipal': 'Hacer principal',
    'fotos.subirPrimera': 'Subir la primera',
    'fotos.agregar': 'Agregar',
    'fotos.a11yUsarPerfil': 'Usar esta como foto de perfil',
    'fotos.a11yQuitar': 'Quitar esta foto',
    'fotos.a11yAgregar': 'Agregar una foto',
    'fotos.yaTienesTitulo': 'Ya tienes {{max}} fotos',
    'fotos.yaTienes': 'Quita una para poder agregar otra.',
    'fotos.permisoTitulo': 'Permiso requerido',
    'fotos.permiso': 'Necesitamos permiso para acceder a tus fotos.',
    'fotos.noSubimosTitulo': 'No pudimos subir la foto',
    'fotos.noSubimos': 'Revisa tu conexión e intenta de nuevo.',
    'fotos.noQuitamosTitulo': 'No pudimos quitarla',
    'fotos.intentaLuego': 'Intenta de nuevo en un momento.',
    'fotos.noCambiamosTitulo': 'No pudimos cambiarla',
    'fotos.quitarTitulo': 'Quitar foto',
    'fotos.quitar': 'Quitar',
    'fotos.quitarPrincipal': 'Es tu foto principal. La siguiente pasará a ocupar su lugar.',
    'fotos.quitarSeguro': '¿Seguro que quieres quitar esta foto?',
    'perfil.anios': '{{n}} años',
    'perfil.rangoAnios': '{{min}}–{{max}} años',
    'perfil.rangoAniosEdit': '{{min}} - {{max}} años',
    'perfil.tocarParaEditar': 'Tocar para editar',

    // ---------- Selector de idioma ----------
    'idioma.titulo': 'Idioma',
    'idioma.espanol': 'Español',
    'idioma.ingles': 'English',

    // ---------- Lote idioma: perfil, soporte, genero ----------
    'comun.exito': 'Éxito',
    'comun.camposRequeridos': 'Campos requeridos',
    'comun.errorConexion': 'Error de conexión',
    'comun.noSePudoGuardar': 'No se pudo guardar',
    'comun.revisaConexion': 'Revisa tu conexión e intenta de nuevo.',
    'perfil.completaCorreoMensaje': 'Por favor completa tu correo y el mensaje',
    'perfil.errorAlEnviar': 'Error al enviar',
    'perfil.noSeEnvioMensaje': 'No se pudo enviar el mensaje. Verifica tu conexión e intenta de nuevo.',
    'perfil.noAbrioWhatsapp': 'No se pudo abrir WhatsApp',
    'perfil.noEliminoCuenta': 'No se pudo eliminar la cuenta. Intenta de nuevo.',
    'perfil.revisaPreferencias': 'Revisa tus preferencias',
    'perfil.minMayorMax': 'El mínimo no puede ser mayor que el máximo.',
    'perfil.completaRequeridos': 'Por favor completa todos los campos requeridos',
    'perfil.noActualizoPerfil': 'No se pudo actualizar el perfil',
    'perfil.perfilActualizado': 'Perfil actualizado correctamente',
    'perfil.contrasenaActualizada': 'Contraseña actualizada correctamente',
    'perfil.verCambiarFotos': 'Ver y cambiar mis fotos',
    'perfil.editarFrase': 'Editar tu frase',
    'perfil.escribirAlgo': 'Escribir algo sobre ti',
    'perfil.cuentaAlgo': '✏️  Cuenta algo sobre ti',
    'perfil.gustosMayus': 'GUSTOS',
    'perfil.rasgosMayus': 'RASGOS',
    'perfil.supervisionVivo': 'Supervisión en vivo',
    'perfil.supervisionSub': 'Dinámica y chats de las mesas de hoy',
    'perfil.correo': 'Correo',
    'perfil.volverSinGuardar': 'Volver sin guardar',
    'perfil.tuNombre': 'Tu nombre',
    'perfil.seleccionaCiudad': 'Selecciona tu ciudad',
    'perfil.contactarSoporte': 'Contactar Soporte',
    'perfil.responderemosPronto': 'Te responderemos lo antes posible',
    'perfil.correoPh': 'tu@correo.com',
    'perfil.mensaje': 'Mensaje',
    'perfil.describeConsulta': 'Describe tu consulta o problema...',
    'perfil.enviando': 'Enviando...',
    'perfil.enviarMensaje': 'Enviar mensaje',
    'perfil.prefNotificaciones': 'Preferencias de Notificaciones',
    'perfil.hombre': 'Hombre',
    'perfil.mujer': 'Mujer',
    'perfil.noBinario': 'No binario',
    'perfil.hombres': 'Hombres',
    'perfil.mujeres': 'Mujeres',
    'perfil.ambos': 'Ambos',
    'perfil.interesadoEn': 'Interesado en',


    // ---------- Ficha de persona ----------
    'ficha.sinFotos': 'Todavía no ha subido fotos',
    'ficha.fotoAnterior': 'Foto anterior',
    'ficha.fotoSiguiente': 'Foto siguiente',
    'ficha.alguien': 'Alguien',
    'ficha.leGusta': 'Le gusta',
    'ficha.comoEs': 'Cómo es',
    'ficha.sinIntereses': 'Todavía no ha contado sus intereses. Pregúntale en el evento 😉',


    // ---------- Suscripcion: alertas, tarjeta, motivos de cancelacion ----------
    'sus.tarjetaIncompleta': 'Por favor completa todos los datos de la tarjeta.',
    'sus.titularCorto': 'El nombre del titular debe tener al menos 5 caracteres.',
    'sus.verifRequerida': 'Verificación requerida',
    'sus.verifRequeridaMsg': 'Tu banco pidió una verificación adicional. Te vamos a redirigir para completarla.',
    'sus.pagoEnVerif': 'Pago en verificación',
    'sus.pagoEnVerifMsg': 'Tu pago sigue siendo verificado por el banco. Se activará automáticamente apenas se confirme; revisa en unos minutos.',
    'sus.cuentanosMotivo': 'Cuéntanos el motivo',
    'sus.cuentanosMotivoMsg': 'Escribe brevemente por qué cancelas para poder mejorar.',
    'sus.seleccionaMotivo': 'Selecciona un motivo',
    'sus.seleccionaMotivoMsg': 'Cuéntanos por qué cancelas para poder seguir mejorando.',
    'sus.noCancelo': 'No se pudo cancelar. Intenta de nuevo.',
    'sus.noReactivo': 'No se pudo reactivar la renovación. Intenta de nuevo.',
    'sus.numeroTarjeta': 'Número de tarjeta',
    'sus.mmaa': 'MM/AA',
    'sus.guardarTarjeta': 'Guardar tarjeta nueva',
    'sus.volverSinCambiar': '← Volver sin cambiar',
    'sus.introSubtitulo': 'Ve a todos los eventos del mes sin volver a pagar por separado',
    'sus.renuevaMes': 'Se renueva cada mes automáticamente. Puedes cancelar la renovación cuando quieras desde tu perfil. Los planes pagados no son reembolsables.',
    'sus.renuevaMeses': 'Se renueva cada {{n}} meses automáticamente. Puedes cancelar la renovación cuando quieras desde tu perfil. Los planes pagados no son reembolsables.',
    'sus.nosAyuda': 'Nos ayuda a mejorar Nospi.',
    'sus.otroMotivoPh': 'Cuéntanos cuál es el motivo',
    'sus.volver': 'Volver',
    'sus.yaPuedesIr': 'Ya puedes ir a todos los eventos del mes sin pagar cada uno por separado.',
    'sus.pagarYActivar': 'Pagar {{precio}} y activar',
    'motivo.costoso': 'Es muy costoso',
    'motivo.pocoUso': 'No lo uso lo suficiente',
    'motivo.alternativa': 'Encontré otra alternativa',
    'motivo.tecnicos': 'Problemas técnicos con la app',
    'motivo.expectativas': 'No cumplió mis expectativas',
    'motivo.otro': 'Otro',


    // ---------- Detalle de evento ----------
    'detalle.noSePudoAbrir': 'No se pudo abrir',
    'detalle.intentaUnosSegundos': 'Intenta de nuevo en unos segundos.',
    'detalle.eventoNoEncontrado': 'Evento no encontrado',
    'detalle.hombresYMujeres': 'Hombres y mujeres',
    'detalle.fecha': '📅 Fecha',
    'detalle.hora': '🕐 Hora',
    'detalle.ciudad': '🌆 Ciudad',
    'detalle.grupo': '👥 Grupo',
    'detalle.videollamadaTitulo': '🎥 Videollamada',
    'detalle.ubicacionTitulo': '📍 Ubicación',
    'detalle.volverVideollamada': 'Volver a la videollamada',
    'detalle.verMiCupo': 'Ver mi cupo',
    'detalle.fechaSinDefinir': 'Fecha sin definir',
    'detalle.pol1': 'ℹ️ Si no vas a poder asistir, puedes ',
    'detalle.polMas24': 'cancelar desde la app con más de 24 horas',
    'detalle.pol2': ' de anticipación y te devolvemos tu ',
    'detalle.polSaldo': 'saldo',
    'detalle.pol3': ' para que lo uses en otro evento. Si lo haces con ',
    'detalle.polMenos24': 'menos de 24 horas',
    'detalle.pol4': ' o ',
    'detalle.polNoAsistes': 'no asistes',
    'detalle.pol5': ', no alcanzamos a devolverte el saldo y tu cuenta podría ',
    'detalle.polSuspendida': 'quedar suspendida',
    'detalle.pol6': ' para reservar por un tiempo.',


    // ---------- Pantalla de pago ----------
    'pago.errorConfirmarCita': 'Error al confirmar cita',
    'pago.errorConfirmarCitaMsg': 'Tu pago fue procesado pero hubo un error al confirmar tu cita. Por favor contacta soporte.',
    'pago.rechazado': 'Pago rechazado',
    'pago.rechazadoMsg': 'Tu pago fue rechazado. Por favor intenta de nuevo.',
    'pago.tarjetaRechazada': 'Tu tarjeta fue rechazada. Por favor verifica los datos e intenta de nuevo.',
    'pago.noSaldoVirtual': 'No se pudo procesar el pago con saldo virtual.',
    'pago.enProceso': 'Pago en proceso',
    'pago.enProcesoMsg': 'Tu pago sigue siendo procesado. Te confirmaremos cuando se complete.',
    'pago.procesando': 'Procesando pago',
    'pago.procesandoMsg': 'Tu pago con tarjeta está siendo verificado. Por favor espera...',
    'pago.celularInvalido': 'Ingresa un número de celular válido de 10 dígitos.',
    'pago.errorEnPago': 'Error en el pago',
    'pago.errorEnPagoMsg': 'Ocurrió un error procesando tu pago. Contacta soporte si el dinero fue debitado.',
    'pago.cancelado': 'Pago cancelado',
    'pago.canceladoMsg': 'Cancelaste el proceso de pago. Si deseas confirmar tu asistencia al evento, por favor intenta realizar el pago nuevamente.',
    'pago.bancoRechazo': 'El banco rechazó tu pago. Por favor, inténtalo de nuevo.',
    'pago.errorProcesando': 'Ocurrió un error al procesar tu pago. Por favor, inténtalo de nuevo.',
    'pago.tiempoAgotado': 'Tiempo agotado',
    'pago.noConfirmoPago': 'No se pudo confirmar el pago. Si realizaste el pago, contacta soporte.',
    'pago.correoPse': 'Ingresa tu correo registrado en PSE.',
    'pago.documentoInvalido': 'Ingresa un número de documento válido.',
    'pago.seleccionaBanco': 'Selecciona tu banco.',
    'pago.nequiSinConfirmar': 'No recibimos confirmación de Nequi. Abre la app de Nequi y aprueba la notificación, luego vuelve aquí e intenta de nuevo.',
    'pago.nequiRechazado': 'El pago fue rechazado por Nequi.',
    'pago.verificandoCuenta': 'Verificando tu cuenta…',
    'pago.verMisCitas': 'Ver mis citas',
    'pago.escribirWhatsapp': 'Escribirnos por WhatsApp',
    'pago.eventoGratis': 'Este evento es gratis',
    'pago.conTarjeta': 'Pagar con Tarjeta',
    'pago.datosTarjeta': '💳 Datos de la tarjeta',
    'pago.nombreTitular': 'Nombre del titular',
    'pago.comoApareceTarjeta': 'Como aparece en la tarjeta',
    'pago.seguroWompi': '🔒 Pago seguro procesado por Wompi',
    'pago.segurosWompi': '🔒 Pagos seguros procesados por Wompi',
    'pago.conNequi': 'Pagar con Nequi',
    'pago.enviarSolicitud': 'Enviar solicitud de pago',
    'pago.revisaNequi': 'Revisa tu app de Nequi',
    'pago.conPse': 'Pagar con PSE',
    'pago.correoPseLabel': 'Correo registrado en PSE',
    'pago.tipoDocumento': 'Tipo de documento',
    'pago.celular': 'Celular',
    'pago.aseguraCupo': 'Asegura tu cupo',
    'pago.comoQuieresIr': '¿Cómo quieres ir?',
    'pago.sinPagarCadaEvento': 'Sin pagar cada evento por separado',
    'pago.cancelaCuandoQuieras': 'Cancela cuando quieras',
    'pago.aplicar': 'Aplicar',
    'pago.volverFlecha': '‹ Volver',
    'pago.pagarEsteEvento': 'Pagar este evento',
    'pago.asistenciaConfirmada': 'Tu asistencia al evento ha sido confirmada',
    'pago.irAPagar': 'Ir a pagar',


    // ---------- Chat ----------
    'chat.videoNoDisponible': '🎥 Video no disponible',
    'chat.fotoNoDisponible': '📷 Foto no disponible',
    'chat.videoEtiqueta': '🎥 Video',
    'chat.fotoEtiqueta': '📷 Foto',
    'chat.audioEtiqueta': '🎤 Nota de voz',
    'chat.mensaje': 'Mensaje',
    'chat.encuesta': 'Encuesta',
    'chat.noRegistroRespuesta': 'No se pudo registrar tu respuesta. ',
    'chat.cargandoEncuesta': 'Cargando encuesta…',
    'chat.respuesta': 'respuesta',
    'chat.respuestas': 'respuestas',
    'chat.promedio': 'Promedio',
    'chat.anonima': 'anónima',
    'chat.cerrada': 'cerrada',
    'chat.puedesCambiar': 'puedes cambiar tu respuesta',
    'chat.fijadoPorNospi': 'Este mensaje lo fijó el equipo de Nospi, así que solo ellos pueden quitarlo.',
    'chat.noFijar': 'No se pudo fijar el mensaje.',
    'chat.noQuitarFijado': 'No se pudo quitar el mensaje de fijados.',
    'chat.mensajesFijados': 'Mensajes fijados',
    'chat.eliminarMensaje': 'Eliminar mensaje',
    'chat.desapareceParaTodos': 'Desaparece para todos. No se puede deshacer.',
    'chat.noSePudo': 'No se pudo',
    'chat.numeroCopiado': 'Número copiado',
    'chat.numeroCopiadoMsg': 'Este dispositivo no permite abrir la tarjeta de contacto, así que copiamos el número.',
    'chat.intentaloDeNuevo': 'Inténtalo de nuevo.',
    'chat.notaDeVoz': 'Nota de voz',
    'chat.noEnvioVideo': 'No se pudo enviar el video',
    'chat.noEnvioFoto': 'No se pudo enviar la foto',
    'chat.revisaConexionIntenta': 'Revisa tu conexión e inténtalo de nuevo.',
    'chat.permisoRequerido': 'Permiso requerido',
    'chat.permisoFotos': 'Necesitamos permiso para acceder a tus fotos y videos.',
    'chat.permisoCamara': 'Necesitamos permiso para usar la cámara.',
    'chat.archivoPesado': 'Archivo muy pesado',
    'chat.imagenPesada': 'Imagen muy pesada',
    'chat.noDisponible': 'No disponible',
    'chat.noPegaImagenes': 'Esta versión de la app todavía no puede pegar imágenes. Se activa con la próxima actualización.',
    'chat.noHayImagen': 'No hay imagen',
    'chat.portapapelesVacio': 'El portapapeles no tiene ninguna imagen copiada.',
    'chat.noSePudoPegar': 'No se pudo pegar',
    'chat.noGuardaArchivos': 'Este dispositivo no permite guardar ni compartir archivos.',
    'chat.guardarVideo': 'Guardar video',
    'chat.guardarFoto': 'Guardar foto',
    'chat.noSePudoGuardar': 'No se pudo guardar',
    'chat.noSePudoCompartir': 'No se pudo compartir',
    'chat.limiteDelDia': 'Llegaste al límite del día',
    'chat.noAbrioChat': 'No se pudo abrir el chat',
    'chat.limiteDetalle': 'Puedes tener hasta 10 solicitudes sin responder. En unas horas se liberan solas, y también se libera cada vez que alguien te acepta.',
    'chat.intentaUnosSegundos': 'Intenta de nuevo en unos segundos.',
    'chat.noPudimosAbrir': 'No pudimos abrir el chat. Vuelve a intentarlo.',
    'chat.chatPrivado': 'Chat privado',
    'chat.aunNoSeHabilita': 'Este chat aún no se habilita',
    'chat.enLinea': 'en línea',
    'chat.cargando': 'Cargando…',
    'chat.verAnteriores': '↑ Ver mensajes anteriores',
    'chat.irUltimoMensaje': 'Ir al último mensaje',
    'chat.todos': 'todos',
    'chat.avisarGrupo': '· avisar a todo el grupo',
    'chat.irRecientes': '↓ Ir a los mensajes recientes',
    'chat.aceptar': 'Aceptar',
    'chat.grabando': 'Grabando… toca ➤ para enviar',
    'chat.buscarGif': 'Buscar un GIF',
    'chat.escribeMensaje': 'Escribe un mensaje...',
    'chat.camara': 'Cámara',
    'chat.fotosYVideos': 'Fotos y videos',
    'chat.enviarGif': 'Enviar un GIF',
    'chat.buscarGifsPh': 'Buscar GIFs: jajaja, abrazo, gracias…',
    'chat.losQueMasUsas': 'Los que más usas',
    'chat.pregunta': 'Pregunta',
    'chat.preguntaPh': '¿A qué hora nos vemos?',
    'chat.agregarOpcion': 'Agregar opción',
    'chat.tocaParaPrivado': 'Toca a alguien para chatear en privado',
    'chat.buscarPorNombre': 'Buscar por nombre',
    'chat.buscarEnConversacion': 'Buscar en esta conversación',
    'chat.alMenosDosLetras': 'Escribe al menos dos letras.',
    'chat.quitarReaccion': 'Toca para quitar tu reacción',
    'chat.verSuPerfil': 'Toca para ver su perfil',
    'chat.verTodosEmojis': 'Ver todos los emojis',
    'chat.infoMensaje': 'Info del mensaje',
    'chat.quitarDeFijados': 'Quitar de fijados',
    'chat.fijarMensaje': 'Fijar mensaje',
    'chat.editar': 'Editar',
    'chat.eliminar': 'Eliminar',
    'chat.nadieMas': 'Todavía no hay nadie más en esta conversación.',
    'chat.escribirPrivado': 'Escribir por privado',
    'chat.escribirWhatsapp': 'Escribir por WhatsApp',
    'chat.copiarNumero': 'Copiar número',
    'chat.videoPalabra': 'Video',
    'chat.fotoPalabra': 'Foto',
    'chat.seElimino': 'Se eliminó a los {{n}} días',

  },

  en: {
    // ---------- Comunes ----------
    'comun.atras': 'Back',
    'comun.cancelar': 'Cancel',
    'comun.aceptar': 'OK',
    'comun.continuar': 'Continue',
    'comun.cerrar': 'Close',
    'comun.error': 'Error',
    'comun.errorInesperado': 'Something went wrong. Please try again.',
    'comun.cargando': 'Loading...',
    'comun.reintentar': 'Try again',
    'comun.faltaUnPaso': 'One more step',

    // ---------- Tipos de evento ----------
    'evento.tipo.bar': 'Bar',
    'evento.tipo.caminata': 'Hike',
    'evento.tipo.cafe': 'Coffee',
    'evento.tipo.bolos': 'Bowling',
    'evento.tipo.virtual': 'Video call',
    'evento.tipo.restaurante': 'Dinner',

    // ---------- Login ----------
    'login.subtituloEntrar': 'Sign in to continue',
    'login.subtituloCrear': 'Join Nospi',
    'login.botonEntrar': 'Sign in',
    'login.botonCrear': 'Create account',
    'login.cambiarAEntrar': 'Already have an account? Sign in',
    'login.cambiarACrear': "Don't have an account? Sign up",
    'login.contrasena': 'Password',
    'login.olvidasteContrasena': 'Forgot your password?',
    'login.faltaEmailOContrasena': 'Please enter your email and password',
    'login.credencialesMalas': 'Wrong email or password',
    'login.errorEntrar': 'Could not sign you in',
    'login.errorEntrarReintenta': "Couldn't sign you in. Please try again.",
    'login.errorCrearReintenta': "Couldn't create your account. Please try again.",
    'login.cuentaNoExiste': "We couldn't find an account using this method. Please sign up first.",
    'login.cuentaYaExiste': 'This account already exists. Just sign in.',
    'login.contrasenaInvalida': "That password won't work. Use at least 8 characters.",
    'login.contrasenaCorta': 'Your password is too short. Use at least 8 characters.',
    'login.cuentaEsDeGoogle': 'You created this account with Google. Tap "Continue with Google" above — you don\'t need a password.',
    'login.cuentaEsDeApple': 'You created this account with Apple. Tap "Continue with Apple" above — you don\'t need a password.',
    'login.canceladoApple': 'Sign-in cancelled',
    'login.errorApple': 'Could not sign in with Apple',
    'login.errorGoogle': 'Could not sign in with Google',

    // ---------- Recuperar contraseña ----------
    'recuperar.titulo': 'Forgot your password?',
    'recuperar.volverAEntrar': 'Back to sign in',

    // ---------- Lista de eventos ----------
    'eventos.estaSemana': 'This week',
    'eventos.proximaSemana': 'Next week',
    'eventos.enDosSemanas': 'In 2 weeks',
    'eventos.masAdelante': 'Later on',
    'eventos.sinFecha': 'Date to be confirmed',
    'eventos.cambiarCiudad': 'Not your city? Change it in your profile',
    'eventos.elegirCiudad': 'Pick your city in your profile',
    'eventos.ubicacionUnDiaAntes': 'Location revealed the day before',

    // ---------- Detalle del evento ----------
    'detalle.titulo': 'Event details',
    'detalle.deseasAsistir': 'Want to join?',
    'detalle.videollamada': '🎥 Video call',
    'detalle.ubicacion': '📍 Location',
    'detalle.irALaDinamica': 'Go to the icebreaker',
    'detalle.yaEstasInscrito': "✓ You're in",
    'detalle.reservado': '✦ BOOKED! ✦',
    'detalle.cupoAsegurado': 'Your spot is saved 🎉',
    'detalle.ubicacionLaEnviamos': "We'll send you the location the day before",
    'detalle.disponibleALas': 'Available at {{hora}}',
    'detalle.disponibleElDia': 'Available on the day of the event',
    'detalle.verPoliticaCompleta': 'Read the full policy',
    'detalle.aceptoBolos': 'I read that the lane and the shoes are paid separately, directly at the bowling alley.',
    'detalle.aceptoGeneral': 'I read the information above and I take part at my own responsibility.',

    'detalle.confirmarAsistencia': 'Confirm attendance',
    'detalle.gratis': 'Free',
    'detalle.marcaCasillaBolos': 'To book, first tick the box above confirming you read that the lane and the shoes are paid separately at the bowling alley.',
    'detalle.marcaCasillaGeneral': 'To book, first tick the box above accepting that you take part at your own responsibility.',

    // ---------- Mis citas ----------
    'citas.elegirConQuienConecte': '💘 Pick who you clicked with',
    'citas.ubicacionUnDiaAntes': 'Location revealed the day before the event',
    'citas.cancelarCita': 'Cancel this booking?',
    'citas.siCancelar': 'Yes, cancel',

    // ---------- Pago ----------
    'pago.verificandoSuscripcion': 'Checking your subscription...',
    'pago.suscripcionActivada': 'Subscription active!',
    'pago.enVerificacion': "Your payment is still being checked. We'll confirm as soon as it goes through.",
    'pago.errorVerificando': 'Something went wrong checking your subscription.',
    'pago.transaccionNoEncontrada': 'Transaction not found.',
    'pago.expiro': 'The payment expired.',
    'pago.aprobado': 'Payment approved! Confirming your spot...',
    'pago.seProcesaAutomaticamente': 'Your payment will go through automatically',

    // ---------- Títulos del onboarding ----------
    'onboarding.gustos': 'Your interests',
    'onboarding.nombre': 'Your name',
    'onboarding.fechaNacimiento': 'Date of birth',
    'onboarding.genero': 'Your gender',
    'onboarding.intereses': 'Looking for',
    'onboarding.edades': 'Ages',
    'onboarding.ubicacion': 'Location',
    'onboarding.compatibilidad': 'Compatibility',
    'onboarding.telefono': 'Phone',
    'onboarding.foto': 'Profile photo',
    'onboarding.registro': 'Sign up',

    // ---------- Idioma de la mesa ----------
    'mesaIdioma.pregunta': 'Which languages are you up for at the table?',
    'mesaIdioma.preguntaSala': 'Which languages are you up for in the room?',
    'mesaIdioma.explicacion': 'We seat you with people who picked the same. You can pick both.',
    'mesaIdioma.explicacionSala': 'We put you in a room with people who picked the same. You can pick both.',
    'mesaIdioma.espanol': 'Spanish',
    'mesaIdioma.ingles': 'English',
    'mesaIdioma.inglesSub': 'With locals who speak it',
    'mesaIdioma.tuCupo': 'Your seat',
    'mesaIdioma.escogeUno': 'Pick at least one language to continue.',

    // ---------- Zona preferida ----------
    'zona.pregunta': 'Which area would you like?',
    'zona.explicacion': 'Tick every one that works for you.',
    'zona.aviso': "This doesn't decide where the event will be. It tells us which areas to open next.",
    'zona.poblado': 'El Poblado',
    'zona.pobladoSub': 'Most dinners happen here',
    'zona.laureles': 'Laureles',
    'zona.laurelesSub': 'Coffee and bowling',
    'zona.envigado': 'Envigado',
    'zona.otra': 'Somewhere else',
    'zona.otraSub': 'Tell us where',
    'zona.otraPlaceholder': 'Which one? Type it',
    'zona.escribeCual': 'Type which area that is so you can continue.',

    'eventos.titulo': 'Events',
    'eventos.enCiudad': 'Events in {{ciudad}}',
    'eventos.todasLasCiudades': 'Events in all cities',
    'eventos.gratis': 'FREE',
    'eventos.camaraPrendidaEnlaceYa': 'Camera on · link already available',
    'eventos.camaraPrendidaEnlaceDespues': 'Camera on · link on the day',
    'eventos.diasCortos': 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    'eventos.mesesCortos': 'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',

    // ---------- Bienvenida ----------
    'bienvenida.tagline1': 'Your weekly dose',
    'bienvenida.tagline2': 'of connection',
    'bienvenida.subtitulo': 'Meet real people at group events, every week',
    'bienvenida.empezar': 'Get started',
    'bienvenida.yaTengoCuenta': 'I already have an account',

    // ---------- Suscripción ----------
    'sus.titulo': 'Nospi monthly subscription',
    'sus.activa': 'Your subscription is active',
    'sus.seRenueva': 'Renews automatically every month',
    'sus.noSeRenueva': "Won't renew — ends on the date shown",
    'sus.metodoPago': 'Payment method',
    'sus.cancelarRenovacion': 'Cancel auto-renewal',
    'sus.reactivarRenovacion': 'Turn auto-renewal back on',
    'sus.recomendado': 'Recommended',
    'sus.masElegido': 'MOST POPULAR',
    'sus.descripcion': 'Unlimited events, every one we run. Pick how long for.',
    'sus.plan1': '1 month',
    'sus.plan3': '3 months',
    'sus.plan6': '6 months',
    'sus.alMes': '{{precio}} a month',
    'sus.ahorras': 'You save {{monto}}',
    'sus.feature1': 'Unlimited access to every event this month',
    'sus.feature2': 'No paying for each event separately',
    'sus.feature3': 'Cancel whenever you want',
    'sus.breakEven': 'Worth it if you go to {{n}}+ events a month',
    'sus.suscribirme': 'Subscribe',
    'sus.porQueCancelas': 'Why are you cancelling?',
    'sus.cancelarSuscripcion': 'Cancel subscription',
    'sus.activada': 'Subscription active!',
    'sus.cancelada': 'Subscription cancelled',
    'sus.canceladaSub': "It won't renew again. You keep access until the end of the period you already paid for.",
    'sus.reactivada': 'Auto-renewal is back on!',
    'sus.reactivadaSub': 'Your subscription will renew automatically each month with the card you already have saved.',
    'sus.nombreTitular': 'Cardholder name',

    // ---------- Perfil ----------
    'perfil.infoPersonal': 'Personal information',
    'perfil.gustos': 'Interests',
    'perfil.intereses': 'Interests',
    'perfil.personalidad': 'Personality',
    'perfil.notificaciones': 'Notification settings',
    'perfil.notificacionesSub': 'Tap to set up',
    'perfil.contrasena': 'Change password',
    'perfil.contrasenaSub': 'Update your password',
    'perfil.suscripcion': 'Nospi monthly subscription',
    'perfil.suscripcionSub': 'Unlimited access to every event this month',
    'perfil.politica': 'Attendance policy',
    'perfil.politicaSub': 'Cancelling, balance and suspensions',
    'perfil.soporte': 'Support',
    'perfil.soporteSub': 'Need a hand? Write to us',

    'perfil.misFotos': 'My photos · {{n}} of 6',
    'perfil.misFotosVacio': 'Add your photos',
    'perfil.misFotosA11y': 'My photos, {{n}} of 6',
    'perfil.editarPerfil': 'Edit profile',
    'perfil.editarPerfilTitulo': 'Edit profile',
    'perfil.telefono': 'Phone',
    'perfil.genero': 'Gender',
    'perfil.ubicacion': 'Location',
    'perfil.rangoEdad': 'Preferred age range',
    'perfil.sinIntereses': "You haven't added any interests yet",
    'perfil.sinRasgos': "You haven't added any personality traits yet",
    'perfil.sobreMi': 'About me',
    'perfil.sobreMiEjemplo': 'E.g. I laugh at everything, I cook better than I dance, and I never say no to a coffee.',
    'perfil.tuTelefono': 'Your phone',
    'perfil.pais': 'Country',
    'perfil.seleccionaPais': 'Pick your country',
    'perfil.buscarPais': 'Search country or code...',
    'perfil.minimo': 'Minimum',
    'perfil.maximo': 'Maximum',
    'perfil.guardarCambios': 'Save changes',
    'perfil.eliminarCuenta': 'Delete account',
    'perfil.cerrarSesion': 'Sign out',
    'perfil.correoSub': 'Send us a message',
    'perfil.whatsappSub': 'Chat with us',
    'perfil.tuCorreo': 'Your email',
    'perfil.mensajeEnviado': 'Message sent!',
    'perfil.notifSubtitulo': 'Choose what you want to get',
    'perfil.sesionCerrada': 'Your session ended. Sign in again to see your profile and confirm your spot.',
    'perfil.sesionCerradaHint': "You're viewing Nospi inside another app (WhatsApp, for example). Open it in Safari, Chrome or the Nospi app to sign in.",
    'perfil.contrasenaSubtitulo': 'Enter your current password and the new one',
    'perfil.contrasenaActual': 'Current password *',
    'perfil.contrasenaActualPh': 'Current password',
    'perfil.contrasenaNueva': 'New password *',
    'perfil.contrasenaNuevaPh': 'New password (at least 6 characters)',
    'perfil.contrasenaConfirmar': 'Confirm new password *',
    'perfil.contrasenaConfirmarPh': 'Confirm the new password',

    // ---------- Notificaciones ----------
    'notif.privadosTitulo': 'Direct messages',
    'notif.privadosAyuda': 'When someone writes to you directly',
    'notif.novedadesTitulo': 'News and new events',
    'notif.novedadesAyuda': 'New events, free spots and Nospi announcements',
    'notif.promocionesTitulo': 'Promotions and discounts',
    'notif.promocionesAyuda': 'Offers and campaigns',
    'notif.mesaTitulo': 'My table chat',
    'notif.mesaAyuda': 'The group with the people at your event',
    'notif.comunidadTitulo': 'Nospi Community',
    'notif.comunidadAyuda': 'The big group, with everyone',
    'notif.modoTodos': 'All',
    'notif.modoMenciones': 'Only if they mention me',
    'notif.modoNinguno': 'None',
    'notif.siempreLlegan': 'Alerts about your bookings — the time, the place, table changes and anything posted in your event channel — always come through.',

    // ---------- Privacidad ----------
    'priv.titulo': 'Privacy',
    'priv.subtitulo': 'Who sees when you are online',
    'priv.enLineaTitulo': 'When I am online',
    'priv.enLineaAyuda': 'Others see a green dot when you have the app open.',
    'priv.ultimaVezTitulo': 'My last seen',
    'priv.ultimaVezAyuda': 'They see when you were last around. For example: "today at 3:40 pm".',

    'priv.reciprocidad': "This decides what others see of you. If you turn something off, you don't see it on them either.",
    'priv.resumenTodoApagado': "Nobody knows when you're online. You don't see it on anyone either.",
    'priv.resumenSinUltimaVez': "Nobody sees your last seen — and you don't see theirs — but the green dot still works both ways.",
    'priv.resumenTodoEncendido': 'You see the green dot and the last seen of everyone who also has it on.',
    'priv.ultimaVezAhora': 'last seen just now',
    'priv.ultimaVezMinutos': 'last seen {{n}} {{unidad}} ago',
    'priv.minuto': 'minute',
    'priv.minutos': 'minutes',
    'priv.ultimaVezHoy': 'last seen today at {{hora}}',
    'priv.ultimaVezAyer': 'last seen yesterday at {{hora}}',
    'priv.ultimaVezDia': 'last seen on {{dia}} at {{hora}}',
    'priv.ultimaVezFecha': 'last seen on {{mes}} {{dia}}',
    'priv.dias': 'Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday',
    'priv.meses': 'January,February,March,April,May,June,July,August,September,October,November,December',
    'priv.am': 'am',
    'priv.pm': 'pm',

    'perfil.nombre': 'Name',
    'perfil.ciudad': 'City',
    'perfil.rangoEdadEtiqueta': 'Ages you feel comfortable with',
    'perfil.rangoEdadAyuda': 'We use this to seat you: the wider the range, the more likely you land with people you click with.',
    'perfil.eliminarPregunta': 'Are you sure you want to delete your account?',
    'perfil.eliminando': 'Deleting...',
    'perfil.siEliminar': 'Yes, delete my account',
    'perfil.sinInfoUsuario': "We couldn't find your account details",
    'perfil.celularRepetido': 'That phone number is already registered to someone else. Please use a different one.',
    'perfil.contrasenaCorta6': 'The new password must be at least 6 characters',
    'perfil.contrasenasNoCoinciden': "The passwords don't match",
    'perfil.contrasenaActualMala': 'Your current password is wrong',

    // ---------- Política de asistencia ----------
    'pol.titulo': 'Attendance policy',
    'pol.lead': 'We make sure every table is full so the night is good for everyone',
    'pol.leadB': "That's why we ask you to tell us in time if you can't make it.",
    'pol.cancelTitulo': '🗓️  Cancelling',
    'pol.cancel1a': "If you can't make it, you can ",
    'pol.cancel1b': 'cancel in the app more than 24 hours',
    'pol.cancel1c': ' ahead and we give you back your ',
    'pol.cancel1d': 'balance',
    'pol.cancel1e': ' to use at another event, with no consequences.',
    'pol.cancel2a': 'If you cancel with ',
    'pol.cancel2b': 'less than 24 hours',
    'pol.cancel2c': ' to go, or if you ',
    'pol.cancel2d': "don't show up",
    'pol.cancel2e': ", we can't return the balance and it counts as ",
    'pol.cancel2f': 'a miss',
    'pol.cancel2g': ' on your account: by then your seat is taken and the group is set.',
    'pol.faltasTitulo': 'How misses are counted',
    'pol.nivel1': 'Warning',
    'pol.nivel1Desc': 'First miss: we just let you know, nothing is blocked.',
    'pol.nivel2': '15-day suspension',
    'pol.nivel2Desc': "Second miss: you can't book for 15 days.",
    'pol.nivel3': '60-day suspension',
    'pol.nivel3Desc': "Third miss: you can't book for 60 days.",
    'pol.nota': 'Misses clear after about 4 months of good standing.',
    'pol.suspTitulo': '🔓  What does suspended mean?',
    'pol.susp1a': 'It only means you ',
    'pol.susp1b': "can't book",
    'pol.susp1c': ' new events for that time. You keep using the app as usual (chat, profile…).',
    'pol.soporteTitulo': '🛟  Something went wrong?',
    'pol.soporte1a': 'If something failed when confirming your spot or getting in, ',
    'pol.soporte1b': 'write to support',
    'pol.soporte1c': ' and we sort it out. We never suspend anyone over a technical glitch or for telling us in time.',

    // ---------- Pago de un evento ----------
    'pag.confirmaAsistencia': 'Confirm your spot',
    'pag.porEvento': 'Per event',
    'pag.porEventoUnidad': '/ event',
    'pag.porEventoSub': 'You pay each time you come to an event.',
    'pag.porMes': '/ month',
    'pag.susSub': 'Unlimited events, every one we run this month.',
    'pag.desdeAlMes': 'or from {{precio}} a month with the 3 and 6 month plans',
    'pag.tienesCodigo': 'Have a promo code?',
    'pag.codigoLabel': 'Promo code',
    'pag.codigoPlaceholder': 'Enter your code',
    'pag.codigoAplicado': 'Code applied',
    'pag.codigoGratis': 'Your spot at this event is free.',
    'pag.codigoDescuento': "It'll come off the total when you pick how to pay.",
    'pag.comoPagar': 'How do you want to pay?',
    'pag.tarjetaCredito': 'Credit card',
    'pag.numeroTarjeta': 'Card number',
    'pag.pagarMonto': 'Pay {{monto}}',
    'pag.nequiDesc': "Enter the phone number registered with Nequi. You'll get a push notification to approve the payment.",
    'pag.celularNequi': 'Nequi phone number',
    'pag.esperando': 'Waiting for confirmation...',
    'pag.apruebaNequi': 'Approve the payment of',
    'pag.apruebaNequiFin': 'in your Nequi app.',
    'pag.numeroDocumento': 'ID number',
    'pag.pagoExitoso': 'Payment successful!',
    'pag.cupoConfirmado': 'Your spot is confirmed!',
    'pag.cupoGratis': 'Your free spot is confirmed!',
    'pag.cupoGratisSub': 'Your promo code covered this event — your place is saved',
    'pag.codigoAplicadoTitulo': 'Code applied!',
    'pag.verPolitica': 'Read the attendance policy',
    'pag.politicaLarga': "If you can't make it, you can cancel in the app more than 24 hours ahead and we give you back your balance to use at another event. With less than 24 hours, or if you don't show up, we can't return the balance and your account may be suspended from booking for a while.",
    'pag.politicaCorta': "If you can't make it, you can cancel in the app more than 24 hours ahead, no problem. With less than 24 hours, or if you don't show up, your account may be suspended from booking for a while.",

    // ---------- Mis fotos ----------
    'fotos.titulo': 'My photos',
    'fotos.ayuda': 'You can upload up to {{max}}. The first one is your profile photo; the rest are seen by the people in your group before the event.',
    'fotos.listo': 'Done',
    'fotos.principal': 'MAIN',
    'fotos.hacerPrincipal': 'Make it the main one',
    'fotos.subirPrimera': 'Upload the first one',
    'fotos.agregar': 'Add',
    'fotos.a11yUsarPerfil': 'Use this as my profile photo',
    'fotos.a11yQuitar': 'Remove this photo',
    'fotos.a11yAgregar': 'Add a photo',
    'fotos.yaTienesTitulo': 'You already have {{max}} photos',
    'fotos.yaTienes': 'Remove one to add another.',
    'fotos.permisoTitulo': 'Permission needed',
    'fotos.permiso': 'We need permission to open your photos.',
    'fotos.noSubimosTitulo': "We couldn't upload the photo",
    'fotos.noSubimos': 'Check your connection and try again.',
    'fotos.noQuitamosTitulo': "We couldn't remove it",
    'fotos.intentaLuego': 'Try again in a moment.',
    'fotos.noCambiamosTitulo': "We couldn't change it",
    'fotos.quitarTitulo': 'Remove photo',
    'fotos.quitar': 'Remove',
    'fotos.quitarPrincipal': 'This is your main photo. The next one will take its place.',
    'fotos.quitarSeguro': 'Remove this photo?',
    'perfil.anios': '{{n}} years old',
    'perfil.rangoAnios': '{{min}}–{{max}} years',
    'perfil.rangoAniosEdit': '{{min}} - {{max}} years',
    'perfil.tocarParaEditar': 'Tap to edit',

    // ---------- Selector de idioma ----------
    'idioma.titulo': 'Language',
    'idioma.espanol': 'Español',
    'idioma.ingles': 'English',

    // ---------- Lote idioma: perfil, soporte, genero ----------
    'comun.exito': 'Success',
    'comun.camposRequeridos': 'Required fields',
    'comun.errorConexion': 'Connection error',
    'comun.noSePudoGuardar': 'Couldn\'t save',
    'comun.revisaConexion': 'Check your connection and try again.',
    'perfil.completaCorreoMensaje': 'Please fill in your email and your message',
    'perfil.errorAlEnviar': 'Couldn\'t send',
    'perfil.noSeEnvioMensaje': 'We couldn\'t send your message. Check your connection and try again.',
    'perfil.noAbrioWhatsapp': 'Couldn\'t open WhatsApp',
    'perfil.noEliminoCuenta': 'We couldn\'t delete your account. Please try again.',
    'perfil.revisaPreferencias': 'Check your preferences',
    'perfil.minMayorMax': 'The minimum can\'t be higher than the maximum.',
    'perfil.completaRequeridos': 'Please fill in all the required fields',
    'perfil.noActualizoPerfil': 'We couldn\'t update your profile',
    'perfil.perfilActualizado': 'Profile updated',
    'perfil.contrasenaActualizada': 'Password updated',
    'perfil.verCambiarFotos': 'View and change my photos',
    'perfil.editarFrase': 'Edit your line',
    'perfil.escribirAlgo': 'Write something about you',
    'perfil.cuentaAlgo': '✏️  Tell us something about you',
    'perfil.gustosMayus': 'LIKES',
    'perfil.rasgosMayus': 'TRAITS',
    'perfil.supervisionVivo': 'Live supervision',
    'perfil.supervisionSub': 'Today\'s tables: game and chats',
    'perfil.correo': 'Email',
    'perfil.volverSinGuardar': 'Go back without saving',
    'perfil.tuNombre': 'Your name',
    'perfil.seleccionaCiudad': 'Select your city',
    'perfil.contactarSoporte': 'Contact support',
    'perfil.responderemosPronto': 'We\'ll get back to you as soon as we can',
    'perfil.correoPh': 'you@email.com',
    'perfil.mensaje': 'Message',
    'perfil.describeConsulta': 'Describe your question or issue...',
    'perfil.enviando': 'Sending...',
    'perfil.enviarMensaje': 'Send message',
    'perfil.prefNotificaciones': 'Notification preferences',
    'perfil.hombre': 'Man',
    'perfil.mujer': 'Woman',
    'perfil.noBinario': 'Non-binary',
    'perfil.hombres': 'Men',
    'perfil.mujeres': 'Women',
    'perfil.ambos': 'Both',
    'perfil.interesadoEn': 'Interested in',


    // ---------- Ficha de persona ----------
    'ficha.sinFotos': 'Hasn\'t uploaded photos yet',
    'ficha.fotoAnterior': 'Previous photo',
    'ficha.fotoSiguiente': 'Next photo',
    'ficha.alguien': 'Someone',
    'ficha.leGusta': 'Into',
    'ficha.comoEs': 'Personality',
    'ficha.sinIntereses': 'Hasn\'t shared their interests yet. Ask them at the event 😉',


    // ---------- Suscripcion: alertas, tarjeta, motivos de cancelacion ----------
    'sus.tarjetaIncompleta': 'Please fill in all the card details.',
    'sus.titularCorto': 'The cardholder\'s name must be at least 5 characters.',
    'sus.verifRequerida': 'Verification required',
    'sus.verifRequeridaMsg': 'Your bank asked for an extra verification step. We’ll redirect you to complete it.',
    'sus.pagoEnVerif': 'Payment under review',
    'sus.pagoEnVerifMsg': 'Your bank is still verifying the payment. It will activate automatically once confirmed — check back in a few minutes.',
    'sus.cuentanosMotivo': 'Tell us why',
    'sus.cuentanosMotivoMsg': 'Write a quick note on why you’re cancelling so we can improve.',
    'sus.seleccionaMotivo': 'Pick a reason',
    'sus.seleccionaMotivoMsg': 'Tell us why you’re cancelling so we can keep improving.',
    'sus.noCancelo': 'We couldn’t cancel it. Please try again.',
    'sus.noReactivo': 'We couldn’t turn renewal back on. Please try again.',
    'sus.numeroTarjeta': 'Card number',
    'sus.mmaa': 'MM/YY',
    'sus.guardarTarjeta': 'Save new card',
    'sus.volverSinCambiar': '← Back without changing',
    'sus.introSubtitulo': 'Go to every event of the month without paying for each one',
    'sus.renuevaMes': 'Renews automatically every month. You can turn renewal off anytime from your profile. Paid plans are non-refundable.',
    'sus.renuevaMeses': 'Renews automatically every {{n}} months. You can turn renewal off anytime from your profile. Paid plans are non-refundable.',
    'sus.nosAyuda': 'It helps us make Nospi better.',
    'sus.otroMotivoPh': 'Tell us the reason',
    'sus.volver': 'Back',
    'sus.yaPuedesIr': 'You can now go to every event of the month without paying for each one.',
    'sus.pagarYActivar': 'Pay {{precio}} and activate',
    'motivo.costoso': 'Too expensive',
    'motivo.pocoUso': 'I don’t use it enough',
    'motivo.alternativa': 'I found another option',
    'motivo.tecnicos': 'Technical problems with the app',
    'motivo.expectativas': 'It didn’t meet my expectations',
    'motivo.otro': 'Other',


    // ---------- Detalle de evento ----------
    'detalle.noSePudoAbrir': 'Couldn\'t open it',
    'detalle.intentaUnosSegundos': 'Try again in a few seconds.',
    'detalle.eventoNoEncontrado': 'Event not found',
    'detalle.hombresYMujeres': 'Men and women',
    'detalle.fecha': '📅 Date',
    'detalle.hora': '🕐 Time',
    'detalle.ciudad': '🌆 City',
    'detalle.grupo': '👥 Group',
    'detalle.videollamadaTitulo': '🎥 Video call',
    'detalle.ubicacionTitulo': '📍 Location',
    'detalle.volverVideollamada': 'Back to the video call',
    'detalle.verMiCupo': 'See my seat',
    'detalle.fechaSinDefinir': 'Date to be confirmed',
    'detalle.pol1': 'ℹ️ If you can’t make it, you can ',
    'detalle.polMas24': 'cancel in the app more than 24 hours',
    'detalle.pol2': ' ahead and we give you back your ',
    'detalle.polSaldo': 'balance',
    'detalle.pol3': ' to use at another event. If you do it with ',
    'detalle.polMenos24': 'less than 24 hours',
    'detalle.pol4': ' to go, or you ',
    'detalle.polNoAsistes': 'don’t show up',
    'detalle.pol5': ', we can’t give the balance back and your account could ',
    'detalle.polSuspendida': 'be suspended',
    'detalle.pol6': ' from booking for a while.',


    // ---------- Pantalla de pago ----------
    'pago.errorConfirmarCita': 'Couldn’t confirm your seat',
    'pago.errorConfirmarCitaMsg': 'Your payment went through but we couldn’t confirm your seat. Please contact support.',
    'pago.rechazado': 'Payment declined',
    'pago.rechazadoMsg': 'Your payment was declined. Please try again.',
    'pago.tarjetaRechazada': 'Your card was declined. Check the details and try again.',
    'pago.noSaldoVirtual': 'We couldn’t pay with your balance.',
    'pago.enProceso': 'Payment in progress',
    'pago.enProcesoMsg': 'Your payment is still processing. We’ll confirm as soon as it completes.',
    'pago.procesando': 'Processing payment',
    'pago.procesandoMsg': 'Your card payment is being verified. Please wait...',
    'pago.celularInvalido': 'Enter a valid 10-digit mobile number.',
    'pago.errorEnPago': 'Payment error',
    'pago.errorEnPagoMsg': 'Something went wrong with your payment. Contact support if you were charged.',
    'pago.cancelado': 'Payment cancelled',
    'pago.canceladoMsg': 'You cancelled the payment. To confirm your seat, please try paying again.',
    'pago.bancoRechazo': 'Your bank declined the payment. Please try again.',
    'pago.errorProcesando': 'Something went wrong processing your payment. Please try again.',
    'pago.tiempoAgotado': 'Timed out',
    'pago.noConfirmoPago': 'We couldn’t confirm the payment. If you were charged, contact support.',
    'pago.correoPse': 'Enter the email you use with PSE.',
    'pago.documentoInvalido': 'Enter a valid ID number.',
    'pago.seleccionaBanco': 'Select your bank.',
    'pago.nequiSinConfirmar': 'We didn’t get a confirmation from Nequi. Open the Nequi app, approve the notification, then come back and try again.',
    'pago.nequiRechazado': 'Nequi declined the payment.',
    'pago.verificandoCuenta': 'Checking your account…',
    'pago.verMisCitas': 'See my bookings',
    'pago.escribirWhatsapp': 'Message us on WhatsApp',
    'pago.eventoGratis': 'This event is free',
    'pago.conTarjeta': 'Pay by card',
    'pago.datosTarjeta': '💳 Card details',
    'pago.nombreTitular': 'Cardholder name',
    'pago.comoApareceTarjeta': 'As it appears on the card',
    'pago.seguroWompi': '🔒 Secure payment processed by Wompi',
    'pago.segurosWompi': '🔒 Secure payments processed by Wompi',
    'pago.conNequi': 'Pay with Nequi',
    'pago.enviarSolicitud': 'Send payment request',
    'pago.revisaNequi': 'Check your Nequi app',
    'pago.conPse': 'Pay with PSE',
    'pago.correoPseLabel': 'Email registered with PSE',
    'pago.tipoDocumento': 'ID type',
    'pago.celular': 'Mobile number',
    'pago.aseguraCupo': 'Secure your seat',
    'pago.comoQuieresIr': 'How do you want to go?',
    'pago.sinPagarCadaEvento': 'No paying for each event separately',
    'pago.cancelaCuandoQuieras': 'Cancel anytime',
    'pago.aplicar': 'Apply',
    'pago.volverFlecha': '‹ Back',
    'pago.pagarEsteEvento': 'Pay for this event',
    'pago.asistenciaConfirmada': 'Your seat at the event is confirmed',
    'pago.irAPagar': 'Go to payment',


    // ---------- Chat ----------
    'chat.videoNoDisponible': '🎥 Video unavailable',
    'chat.fotoNoDisponible': '📷 Photo unavailable',
    'chat.videoEtiqueta': '🎥 Video',
    'chat.fotoEtiqueta': '📷 Photo',
    'chat.audioEtiqueta': '🎤 Voice note',
    'chat.mensaje': 'Message',
    'chat.encuesta': 'Poll',
    'chat.noRegistroRespuesta': 'We couldn’t save your answer. ',
    'chat.cargandoEncuesta': 'Loading poll…',
    'chat.respuesta': 'answer',
    'chat.respuestas': 'answers',
    'chat.promedio': 'Average',
    'chat.anonima': 'anonymous',
    'chat.cerrada': 'closed',
    'chat.puedesCambiar': 'you can change your answer',
    'chat.fijadoPorNospi': 'The Nospi team pinned this message, so only they can unpin it.',
    'chat.noFijar': 'We couldn’t pin the message.',
    'chat.noQuitarFijado': 'We couldn’t unpin the message.',
    'chat.mensajesFijados': 'Pinned messages',
    'chat.eliminarMensaje': 'Delete message',
    'chat.desapareceParaTodos': 'It disappears for everyone. This can’t be undone.',
    'chat.noSePudo': 'Couldn’t do it',
    'chat.numeroCopiado': 'Number copied',
    'chat.numeroCopiadoMsg': 'This device can’t open the contact card, so we copied the number instead.',
    'chat.intentaloDeNuevo': 'Please try again.',
    'chat.notaDeVoz': 'Voice note',
    'chat.noEnvioVideo': 'Couldn’t send the video',
    'chat.noEnvioFoto': 'Couldn’t send the photo',
    'chat.revisaConexionIntenta': 'Check your connection and try again.',
    'chat.permisoRequerido': 'Permission needed',
    'chat.permisoFotos': 'We need permission to access your photos and videos.',
    'chat.permisoCamara': 'We need permission to use the camera.',
    'chat.archivoPesado': 'File too large',
    'chat.imagenPesada': 'Image too large',
    'chat.noDisponible': 'Not available',
    'chat.noPegaImagenes': 'This version of the app can’t paste images yet. It arrives with the next update.',
    'chat.noHayImagen': 'No image',
    'chat.portapapelesVacio': 'There’s no image on the clipboard.',
    'chat.noSePudoPegar': 'Couldn’t paste',
    'chat.noGuardaArchivos': 'This device can’t save or share files.',
    'chat.guardarVideo': 'Save video',
    'chat.guardarFoto': 'Save photo',
    'chat.noSePudoGuardar': 'Couldn’t save',
    'chat.noSePudoCompartir': 'Couldn’t share',
    'chat.limiteDelDia': 'You’ve hit today’s limit',
    'chat.noAbrioChat': 'Couldn’t open the chat',
    'chat.limiteDetalle': 'You can have up to 10 pending requests. They free up on their own in a few hours, and each time someone accepts you.',
    'chat.intentaUnosSegundos': 'Try again in a few seconds.',
    'chat.noPudimosAbrir': 'We couldn’t open the chat. Please try again.',
    'chat.chatPrivado': 'Private chat',
    'chat.aunNoSeHabilita': 'This chat isn’t open yet',
    'chat.enLinea': 'online',
    'chat.cargando': 'Loading…',
    'chat.verAnteriores': '↑ See earlier messages',
    'chat.irUltimoMensaje': 'Go to the latest message',
    'chat.todos': 'everyone',
    'chat.avisarGrupo': '· notify the whole group',
    'chat.irRecientes': '↓ Go to recent messages',
    'chat.aceptar': 'Accept',
    'chat.grabando': 'Recording… tap ➤ to send',
    'chat.buscarGif': 'Search for a GIF',
    'chat.escribeMensaje': 'Write a message...',
    'chat.camara': 'Camera',
    'chat.fotosYVideos': 'Photos and videos',
    'chat.enviarGif': 'Send a GIF',
    'chat.buscarGifsPh': 'Search GIFs: lol, hug, thanks…',
    'chat.losQueMasUsas': 'Your most used',
    'chat.pregunta': 'Question',
    'chat.preguntaPh': 'What time should we meet?',
    'chat.agregarOpcion': 'Add option',
    'chat.tocaParaPrivado': 'Tap someone to chat privately',
    'chat.buscarPorNombre': 'Search by name',
    'chat.buscarEnConversacion': 'Search in this conversation',
    'chat.alMenosDosLetras': 'Type at least two letters.',
    'chat.quitarReaccion': 'Tap to remove your reaction',
    'chat.verSuPerfil': 'Tap to see their profile',
    'chat.verTodosEmojis': 'See all emojis',
    'chat.infoMensaje': 'Message info',
    'chat.quitarDeFijados': 'Unpin',
    'chat.fijarMensaje': 'Pin message',
    'chat.editar': 'Edit',
    'chat.eliminar': 'Delete',
    'chat.nadieMas': 'There’s nobody else in this conversation yet.',
    'chat.escribirPrivado': 'Message privately',
    'chat.escribirWhatsapp': 'Message on WhatsApp',
    'chat.copiarNumero': 'Copy number',
    'chat.videoPalabra': 'Video',
    'chat.fotoPalabra': 'Photo',
    'chat.seElimino': 'Deleted after {{n}} days',

  },
};
