// Diccionario de textos de Nospi en español e ingles.
//
// Reglas al agregar textos:
//   - La clave se nombra pantalla.loQueEs  (ej: 'login.entrar')
//   - Si falta la traduccion en ingles, la app muestra el español. No se rompe.
//   - Las variables van como {{nombre}} y se pasan en el segundo argumento:
//       t('detalle.disponibleALas', { hora: '7:00 PM' })
//   - El ingles NO es traduccion literal: esta escrito como lo diria un gringo.

import type { Idioma } from '@/lib/i18n';

export const TEXTOS: Record<Idioma, Record<string, string>> = {
  es: {
    // ---------- Comunes ----------
    'comun.atras': 'Atrás',
    'comun.cancelar': 'Cancelar',
    'comun.aceptar': 'Aceptar',
    'comun.continuar': 'Continuar',
    'comun.cerrar': 'Cerrar',
    'comun.error': 'Error',
    'comun.errorInesperado': 'Ocurrió un error inesperado. Por favor, intenta de nuevo.',
    'comun.cargando': 'Cargando...',
    'comun.reintentar': 'Reintentar',
    'comun.faltaUnPaso': 'Falta un paso',

    // ---------- Tipos de evento ----------
    'evento.tipo.bar': 'Bar',
    'evento.tipo.caminata': 'Caminata',
    'evento.tipo.cafe': 'Café',
    'evento.tipo.bolos': 'Bolos',
    'evento.tipo.virtual': 'Videollamada',
    'evento.tipo.restaurante': 'Restaurante',

    // ---------- Login ----------
    'login.subtituloEntrar': 'Inicia sesión para continuar',
    'login.subtituloCrear': 'Únete a Nospi',
    'login.botonEntrar': 'Iniciar sesión',
    'login.botonCrear': 'Crear cuenta',
    'login.cambiarAEntrar': '¿Ya tienes cuenta? Inicia sesión',
    'login.cambiarACrear': '¿No tienes cuenta? Regístrate',
    'login.contrasena': 'Contraseña',
    'login.olvidasteContrasena': '¿Olvidaste tu contraseña?',
    'login.faltaEmailOContrasena': 'Por favor ingresa tu email y contraseña',
    'login.credencialesMalas': 'Email o contraseña incorrectos',
    'login.errorEntrar': 'Error al iniciar sesión',
    'login.errorEntrarReintenta': 'Error al iniciar sesión. Intenta de nuevo.',
    'login.errorCrearReintenta': 'Error al crear cuenta. Intenta de nuevo.',
    'login.cuentaNoExiste': 'No encontramos una cuenta registrada con este método. Por favor regístrate primero.',
    'login.cuentaYaExiste': 'Esta cuenta ya está registrada. Inicia sesión directamente.',
    'login.contrasenaInvalida': 'Esa contraseña no es válida. Usa al menos 8 caracteres.',
    'login.contrasenaCorta': 'Tu contraseña es muy corta. Usa al menos 8 caracteres.',
    'login.cuentaEsDeGoogle': 'Esta cuenta la creaste con Google. Toca "Continuar con Google" (arriba) para entrar — no necesitas contraseña.',
    'login.cuentaEsDeApple': 'Esta cuenta la creaste con Apple. Toca "Continuar con Apple" (arriba) para entrar — no necesitas contraseña.',
    'login.canceladoApple': 'Inicio de sesión cancelado',
    'login.errorApple': 'Error al iniciar sesión con Apple',
    'login.errorGoogle': 'Error al iniciar sesión con Google',

    // ---------- Recuperar contraseña ----------
    'recuperar.titulo': '¿Olvidaste tu contraseña?',
    'recuperar.volverAEntrar': 'Volver a iniciar sesión',

    // ---------- Lista de eventos ----------
    'eventos.estaSemana': 'Esta semana',
    'eventos.proximaSemana': 'La próxima semana',
    'eventos.enDosSemanas': 'En 2 semanas',
    'eventos.masAdelante': 'Más adelante',
    'eventos.sinFecha': 'Fecha sin definir',
    'eventos.cambiarCiudad': '¿No es tu ciudad? Cámbiala en tu perfil',
    'eventos.elegirCiudad': 'Elige tu ciudad en tu perfil',
    'eventos.ubicacionUnDiaAntes': 'Ubicación se revelará un día antes',

    // ---------- Detalle del evento ----------
    'detalle.titulo': 'Detalles del Evento',
    'detalle.deseasAsistir': '¿Deseas asistir?',
    'detalle.videollamada': '🎥 Videollamada',
    'detalle.ubicacion': '📍 Ubicación',
    'detalle.irALaDinamica': 'Ir a la Dinámica',
    'detalle.yaEstasInscrito': '✓ Ya estás inscrito',
    'detalle.reservado': '✦ ¡RESERVADO! ✦',
    'detalle.cupoAsegurado': 'Tu cupo está asegurado 🎉',
    'detalle.ubicacionLaEnviamos': 'Te enviaremos la ubicación un día antes',
    'detalle.disponibleALas': 'Disponible a las {{hora}}',
    'detalle.disponibleElDia': 'Disponible el día del evento',
    'detalle.verPoliticaCompleta': 'Ver política completa',
    'detalle.aceptoBolos': 'Leí que la pista y los zapatos se pagan aparte, directamente en la bolera.',
    'detalle.aceptoGeneral': 'Leí la información anterior y acepto participar bajo mi propia responsabilidad.',

    'detalle.confirmarAsistencia': 'Confirmar Asistencia',
    'detalle.gratis': 'Gratis',
    'detalle.marcaCasillaBolos': 'Para reservar primero marca la casilla de arriba confirmando que leíste que la pista y los zapatos se pagan aparte en la bolera.',
    'detalle.marcaCasillaGeneral': 'Para reservar primero marca la casilla de arriba aceptando participar bajo tu propia responsabilidad.',

    // ---------- Mis citas ----------
    'citas.elegirConQuienConecte': '💘 Elegir con quién conecté',
    'citas.ubicacionUnDiaAntes': 'Ubicación se revelará un día antes del evento',
    'citas.cancelarCita': '¿Cancelar Cita?',
    'citas.siCancelar': 'Sí, cancelar',

    // ---------- Pago ----------
    'pago.verificandoSuscripcion': 'Verificando tu suscripción...',
    'pago.suscripcionActivada': '¡Suscripción activada!',
    'pago.enVerificacion': 'Tu pago sigue en verificación. Te confirmaremos apenas se complete.',
    'pago.errorVerificando': 'Error verificando tu suscripción.',
    'pago.transaccionNoEncontrada': 'No se encontró la transacción.',
    'pago.expiro': 'El pago expiró.',
    'pago.aprobado': '¡Pago aprobado! Confirmando asistencia...',
    'pago.seProcesaAutomaticamente': 'Tu pago se procesará automáticamente',

    // ---------- Títulos del onboarding ----------
    'onboarding.gustos': 'Tus Gustos',
    'onboarding.nombre': 'Tu Nombre',
    'onboarding.fechaNacimiento': 'Fecha de Nacimiento',
    'onboarding.genero': 'Tu Género',
    'onboarding.intereses': 'Intereses',
    'onboarding.edades': 'Edades',
    'onboarding.ubicacion': 'Ubicación',
    'onboarding.compatibilidad': 'Compatibilidad',
    'onboarding.telefono': 'Teléfono',
    'onboarding.foto': 'Foto de Perfil',
    'onboarding.registro': 'Registro',

    // ---------- Idioma de la mesa ----------
    'mesaIdioma.pregunta': '¿En qué idiomas estás dispuesto a hablar en la mesa?',
    'mesaIdioma.explicacion': 'Te sentamos con gente que escogió lo mismo. Puedes marcar los dos.',
    'mesaIdioma.espanol': 'Español',
    'mesaIdioma.ingles': 'Inglés',
    'mesaIdioma.inglesSub': 'Mesa con gente de afuera',
    'mesaIdioma.tuCupo': 'Tu cupo',
    'mesaIdioma.escogeUno': 'Escoge al menos un idioma para continuar.',

    // ---------- Zona preferida ----------
    'zona.pregunta': '¿En qué zona te gustaría?',
    'zona.explicacion': 'Marca todas las que te sirvan.',
    'zona.aviso': 'Esto no define dónde será el evento. Nos sirve para saber a qué zonas abrir más adelante.',
    'zona.poblado': 'El Poblado',
    'zona.pobladoSub': 'La mayoría de las cenas',
    'zona.laureles': 'Laureles',
    'zona.laurelesSub': 'Cafés y bolos',
    'zona.envigado': 'Envigado',
    'zona.otra': 'Otra',
    'zona.otraSub': 'Dinos cuál',
    'zona.otraPlaceholder': '¿Cuál? Escríbela',

    'eventos.titulo': 'Eventos Disponibles',
    'eventos.enCiudad': 'Eventos en {{ciudad}}',
    'eventos.todasLasCiudades': 'Eventos de todas las ciudades',
    'eventos.gratis': 'GRATIS',
    'eventos.camaraPrendidaEnlaceYa': 'Con cámara prendida · enlace ya disponible',
    'eventos.camaraPrendidaEnlaceDespues': 'Con cámara prendida · enlace el mismo día',
    'eventos.diasCortos': 'Dom,Lun,Mar,Mié,Jue,Vie,Sáb',
    'eventos.mesesCortos': 'ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic',

    // ---------- Bienvenida ----------
    'bienvenida.tagline1': 'Tu dosis semanal',
    'bienvenida.tagline2': 'de conexión',
    'bienvenida.subtitulo': 'Conoce personas reales en encuentros grupales cada semana',
    'bienvenida.empezar': 'Empezar',
    'bienvenida.yaTengoCuenta': 'Ya tengo una cuenta',

    // ---------- Suscripción ----------
    'sus.titulo': 'Suscripción mensual Nospi',
    'sus.activa': 'Tu suscripción está activa',
    'sus.seRenueva': 'Se renueva automáticamente cada mes',
    'sus.noSeRenueva': 'No se renovará — termina en la fecha indicada',
    'sus.metodoPago': 'Método de pago',
    'sus.cancelarRenovacion': 'Cancelar renovación automática',
    'sus.reactivarRenovacion': 'Reactivar renovación automática',
    'sus.recomendado': 'Recomendado',
    'sus.masElegido': 'MÁS ELEGIDO',
    'sus.descripcion': 'Eventos ilimitados, todos los que hagamos. Escoge por cuánto tiempo.',
    'sus.plan1': '1 mes',
    'sus.plan3': '3 meses',
    'sus.plan6': '6 meses',
    'sus.alMes': '{{precio}} al mes',
    'sus.ahorras': 'Ahorras {{monto}}',
    'sus.feature1': 'Acceso sin límite a todos los eventos del mes',
    'sus.feature2': 'Sin pagar cada evento por separado',
    'sus.feature3': 'Cancela cuando quieras',
    'sus.breakEven': 'Te conviene si vas a {{n}}+ eventos al mes',
    'sus.suscribirme': 'Suscribirme',
    'sus.porQueCancelas': '¿Por qué cancelas?',
    'sus.cancelarSuscripcion': 'Cancelar suscripción',
    'sus.activada': '¡Suscripción activada!',
    'sus.cancelada': 'Suscripción cancelada',
    'sus.canceladaSub': 'Dejarás de renovar automáticamente. Conservas el acceso hasta el final del período ya pagado.',
    'sus.reactivada': '¡Renovación reactivada!',
    'sus.reactivadaSub': 'Tu suscripción volverá a renovarse automáticamente cada mes con la tarjeta que ya tenías registrada.',
    'sus.nombreTitular': 'Nombre del titular',

    // ---------- Perfil ----------
    'perfil.infoPersonal': 'Información Personal',
    'perfil.gustos': 'Gustos',
    'perfil.intereses': 'Intereses',
    'perfil.personalidad': 'Personalidad',
    'perfil.notificaciones': 'Preferencias de Notificaciones',
    'perfil.notificacionesSub': 'Toca para configurar',
    'perfil.contrasena': 'Cambiar Contraseña',
    'perfil.contrasenaSub': 'Actualiza tu contraseña',
    'perfil.suscripcion': 'Suscripción mensual Nospi',
    'perfil.suscripcionSub': 'Acceso ilimitado a todos los eventos del mes',
    'perfil.politica': 'Política de asistencia',
    'perfil.politicaSub': 'Cancelación, saldo y suspensiones',
    'perfil.soporte': 'Soporte',
    'perfil.soporteSub': '¿Necesitas ayuda? Contáctanos',

    'perfil.misFotos': 'Mis fotos · {{n}} de 6',
    'perfil.misFotosVacio': 'Agrega tus fotos',
    'perfil.misFotosA11y': 'Mis fotos, {{n}} de 6',
    'perfil.editarPerfil': 'Editar perfil',
    'perfil.editarPerfilTitulo': 'Editar Perfil',
    'perfil.telefono': 'Teléfono',
    'perfil.genero': 'Género',
    'perfil.ubicacion': 'Ubicación',
    'perfil.rangoEdad': 'Rango de edad preferido',
    'perfil.sinIntereses': 'No has agregado intereses aún',
    'perfil.sinRasgos': 'No has agregado rasgos de personalidad aún',
    'perfil.sobreMi': 'Sobre mí',
    'perfil.sobreMiEjemplo': 'Ej: Me río de todo, cocino mejor de lo que bailo y siempre digo que sí a un café.',
    'perfil.tuTelefono': 'Tu teléfono',
    'perfil.pais': 'País',
    'perfil.seleccionaPais': 'Selecciona tu país',
    'perfil.buscarPais': 'Buscar país o código...',
    'perfil.minimo': 'Mínimo',
    'perfil.maximo': 'Máximo',
    'perfil.guardarCambios': 'Guardar Cambios',
    'perfil.eliminarCuenta': 'Eliminar Cuenta',
    'perfil.cerrarSesion': 'Cerrar Sesión',
    'perfil.correoSub': 'Envíanos un mensaje',
    'perfil.whatsappSub': 'Chatea con nosotros',
    'perfil.tuCorreo': 'Tu correo electrónico',
    'perfil.mensajeEnviado': '¡Mensaje enviado!',
    'perfil.notifSubtitulo': 'Elige qué quieres que te llegue',
    'perfil.sesionCerrada': 'Tu sesión se cerró. Inicia sesión de nuevo para ver tu perfil y confirmar tu asistencia.',
    'perfil.sesionCerradaHint': 'Estás viendo Nospi dentro de otra app (por ejemplo WhatsApp). Ábrelo en Safari, Chrome o en la app de Nospi para poder iniciar sesión.',
    'perfil.contrasenaSubtitulo': 'Ingresa tu contraseña actual y la nueva',
    'perfil.contrasenaActual': 'Contraseña Actual *',
    'perfil.contrasenaActualPh': 'Contraseña actual',
    'perfil.contrasenaNueva': 'Nueva Contraseña *',
    'perfil.contrasenaNuevaPh': 'Nueva contraseña (mínimo 6 caracteres)',
    'perfil.contrasenaConfirmar': 'Confirmar Nueva Contraseña *',
    'perfil.contrasenaConfirmarPh': 'Confirma la nueva contraseña',

    // ---------- Selector de idioma ----------
    'idioma.titulo': 'Idioma',
    'idioma.espanol': 'Español',
    'idioma.ingles': 'English',
  },

  en: {
    // ---------- Comunes ----------
    'comun.atras': 'Back',
    'comun.cancelar': 'Cancel',
    'comun.aceptar': 'OK',
    'comun.continuar': 'Continue',
    'comun.cerrar': 'Close',
    'comun.error': 'Error',
    'comun.errorInesperado': 'Something went wrong. Please try again.',
    'comun.cargando': 'Loading...',
    'comun.reintentar': 'Try again',
    'comun.faltaUnPaso': 'One more step',

    // ---------- Tipos de evento ----------
    'evento.tipo.bar': 'Bar',
    'evento.tipo.caminata': 'Hike',
    'evento.tipo.cafe': 'Coffee',
    'evento.tipo.bolos': 'Bowling',
    'evento.tipo.virtual': 'Video call',
    'evento.tipo.restaurante': 'Dinner',

    // ---------- Login ----------
    'login.subtituloEntrar': 'Sign in to continue',
    'login.subtituloCrear': 'Join Nospi',
    'login.botonEntrar': 'Sign in',
    'login.botonCrear': 'Create account',
    'login.cambiarAEntrar': 'Already have an account? Sign in',
    'login.cambiarACrear': "Don't have an account? Sign up",
    'login.contrasena': 'Password',
    'login.olvidasteContrasena': 'Forgot your password?',
    'login.faltaEmailOContrasena': 'Please enter your email and password',
    'login.credencialesMalas': 'Wrong email or password',
    'login.errorEntrar': 'Could not sign you in',
    'login.errorEntrarReintenta': "Couldn't sign you in. Please try again.",
    'login.errorCrearReintenta': "Couldn't create your account. Please try again.",
    'login.cuentaNoExiste': "We couldn't find an account using this method. Please sign up first.",
    'login.cuentaYaExiste': 'This account already exists. Just sign in.',
    'login.contrasenaInvalida': "That password won't work. Use at least 8 characters.",
    'login.contrasenaCorta': 'Your password is too short. Use at least 8 characters.',
    'login.cuentaEsDeGoogle': 'You created this account with Google. Tap "Continue with Google" above — you don\'t need a password.',
    'login.cuentaEsDeApple': 'You created this account with Apple. Tap "Continue with Apple" above — you don\'t need a password.',
    'login.canceladoApple': 'Sign-in cancelled',
    'login.errorApple': 'Could not sign in with Apple',
    'login.errorGoogle': 'Could not sign in with Google',

    // ---------- Recuperar contraseña ----------
    'recuperar.titulo': 'Forgot your password?',
    'recuperar.volverAEntrar': 'Back to sign in',

    // ---------- Lista de eventos ----------
    'eventos.estaSemana': 'This week',
    'eventos.proximaSemana': 'Next week',
    'eventos.enDosSemanas': 'In 2 weeks',
    'eventos.masAdelante': 'Later on',
    'eventos.sinFecha': 'Date to be confirmed',
    'eventos.cambiarCiudad': 'Not your city? Change it in your profile',
    'eventos.elegirCiudad': 'Pick your city in your profile',
    'eventos.ubicacionUnDiaAntes': 'Location revealed the day before',

    // ---------- Detalle del evento ----------
    'detalle.titulo': 'Event details',
    'detalle.deseasAsistir': 'Want to join?',
    'detalle.videollamada': '🎥 Video call',
    'detalle.ubicacion': '📍 Location',
    'detalle.irALaDinamica': 'Go to the icebreaker',
    'detalle.yaEstasInscrito': "✓ You're in",
    'detalle.reservado': '✦ BOOKED! ✦',
    'detalle.cupoAsegurado': 'Your spot is saved 🎉',
    'detalle.ubicacionLaEnviamos': "We'll send you the location the day before",
    'detalle.disponibleALas': 'Available at {{hora}}',
    'detalle.disponibleElDia': 'Available on the day of the event',
    'detalle.verPoliticaCompleta': 'Read the full policy',
    'detalle.aceptoBolos': 'I read that the lane and the shoes are paid separately, directly at the bowling alley.',
    'detalle.aceptoGeneral': 'I read the information above and I take part at my own responsibility.',

    'detalle.confirmarAsistencia': 'Confirm attendance',
    'detalle.gratis': 'Free',
    'detalle.marcaCasillaBolos': 'To book, first tick the box above confirming you read that the lane and the shoes are paid separately at the bowling alley.',
    'detalle.marcaCasillaGeneral': 'To book, first tick the box above accepting that you take part at your own responsibility.',

    // ---------- Mis citas ----------
    'citas.elegirConQuienConecte': '💘 Pick who you clicked with',
    'citas.ubicacionUnDiaAntes': 'Location revealed the day before the event',
    'citas.cancelarCita': 'Cancel this booking?',
    'citas.siCancelar': 'Yes, cancel',

    // ---------- Pago ----------
    'pago.verificandoSuscripcion': 'Checking your subscription...',
    'pago.suscripcionActivada': 'Subscription active!',
    'pago.enVerificacion': "Your payment is still being checked. We'll confirm as soon as it goes through.",
    'pago.errorVerificando': 'Something went wrong checking your subscription.',
    'pago.transaccionNoEncontrada': 'Transaction not found.',
    'pago.expiro': 'The payment expired.',
    'pago.aprobado': 'Payment approved! Confirming your spot...',
    'pago.seProcesaAutomaticamente': 'Your payment will go through automatically',

    // ---------- Títulos del onboarding ----------
    'onboarding.gustos': 'Your interests',
    'onboarding.nombre': 'Your name',
    'onboarding.fechaNacimiento': 'Date of birth',
    'onboarding.genero': 'Your gender',
    'onboarding.intereses': 'Looking for',
    'onboarding.edades': 'Ages',
    'onboarding.ubicacion': 'Location',
    'onboarding.compatibilidad': 'Compatibility',
    'onboarding.telefono': 'Phone',
    'onboarding.foto': 'Profile photo',
    'onboarding.registro': 'Sign up',

    // ---------- Idioma de la mesa ----------
    'mesaIdioma.pregunta': 'Which languages are you up for at the table?',
    'mesaIdioma.explicacion': 'We seat you with people who picked the same. You can pick both.',
    'mesaIdioma.espanol': 'Spanish',
    'mesaIdioma.ingles': 'English',
    'mesaIdioma.inglesSub': 'Table with locals who speak it',
    'mesaIdioma.tuCupo': 'Your seat',
    'mesaIdioma.escogeUno': 'Pick at least one language to continue.',

    // ---------- Zona preferida ----------
    'zona.pregunta': 'Which area would you like?',
    'zona.explicacion': 'Tick every one that works for you.',
    'zona.aviso': "This doesn't decide where the event will be. It tells us which areas to open next.",
    'zona.poblado': 'El Poblado',
    'zona.pobladoSub': 'Most dinners happen here',
    'zona.laureles': 'Laureles',
    'zona.laurelesSub': 'Coffee and bowling',
    'zona.envigado': 'Envigado',
    'zona.otra': 'Somewhere else',
    'zona.otraSub': 'Tell us where',
    'zona.otraPlaceholder': 'Which one? Type it',

    'eventos.titulo': 'Events',
    'eventos.enCiudad': 'Events in {{ciudad}}',
    'eventos.todasLasCiudades': 'Events in all cities',
    'eventos.gratis': 'FREE',
    'eventos.camaraPrendidaEnlaceYa': 'Camera on · link already available',
    'eventos.camaraPrendidaEnlaceDespues': 'Camera on · link on the day',
    'eventos.diasCortos': 'Sun,Mon,Tue,Wed,Thu,Fri,Sat',
    'eventos.mesesCortos': 'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',

    // ---------- Bienvenida ----------
    'bienvenida.tagline1': 'Your weekly dose',
    'bienvenida.tagline2': 'of connection',
    'bienvenida.subtitulo': 'Meet real people at group events, every week',
    'bienvenida.empezar': 'Get started',
    'bienvenida.yaTengoCuenta': 'I already have an account',

    // ---------- Suscripción ----------
    'sus.titulo': 'Nospi monthly subscription',
    'sus.activa': 'Your subscription is active',
    'sus.seRenueva': 'Renews automatically every month',
    'sus.noSeRenueva': "Won't renew — ends on the date shown",
    'sus.metodoPago': 'Payment method',
    'sus.cancelarRenovacion': 'Cancel auto-renewal',
    'sus.reactivarRenovacion': 'Turn auto-renewal back on',
    'sus.recomendado': 'Recommended',
    'sus.masElegido': 'MOST POPULAR',
    'sus.descripcion': 'Unlimited events, every one we run. Pick how long for.',
    'sus.plan1': '1 month',
    'sus.plan3': '3 months',
    'sus.plan6': '6 months',
    'sus.alMes': '{{precio}} a month',
    'sus.ahorras': 'You save {{monto}}',
    'sus.feature1': 'Unlimited access to every event this month',
    'sus.feature2': 'No paying for each event separately',
    'sus.feature3': 'Cancel whenever you want',
    'sus.breakEven': 'Worth it if you go to {{n}}+ events a month',
    'sus.suscribirme': 'Subscribe',
    'sus.porQueCancelas': 'Why are you cancelling?',
    'sus.cancelarSuscripcion': 'Cancel subscription',
    'sus.activada': 'Subscription active!',
    'sus.cancelada': 'Subscription cancelled',
    'sus.canceladaSub': "It won't renew again. You keep access until the end of the period you already paid for.",
    'sus.reactivada': 'Auto-renewal is back on!',
    'sus.reactivadaSub': 'Your subscription will renew automatically each month with the card you already have saved.',
    'sus.nombreTitular': 'Cardholder name',

    // ---------- Perfil ----------
    'perfil.infoPersonal': 'Personal information',
    'perfil.gustos': 'Interests',
    'perfil.intereses': 'Interests',
    'perfil.personalidad': 'Personality',
    'perfil.notificaciones': 'Notification settings',
    'perfil.notificacionesSub': 'Tap to set up',
    'perfil.contrasena': 'Change password',
    'perfil.contrasenaSub': 'Update your password',
    'perfil.suscripcion': 'Nospi monthly subscription',
    'perfil.suscripcionSub': 'Unlimited access to every event this month',
    'perfil.politica': 'Attendance policy',
    'perfil.politicaSub': 'Cancelling, balance and suspensions',
    'perfil.soporte': 'Support',
    'perfil.soporteSub': 'Need a hand? Write to us',

    'perfil.misFotos': 'My photos · {{n}} of 6',
    'perfil.misFotosVacio': 'Add your photos',
    'perfil.misFotosA11y': 'My photos, {{n}} of 6',
    'perfil.editarPerfil': 'Edit profile',
    'perfil.editarPerfilTitulo': 'Edit profile',
    'perfil.telefono': 'Phone',
    'perfil.genero': 'Gender',
    'perfil.ubicacion': 'Location',
    'perfil.rangoEdad': 'Preferred age range',
    'perfil.sinIntereses': "You haven't added any interests yet",
    'perfil.sinRasgos': "You haven't added any personality traits yet",
    'perfil.sobreMi': 'About me',
    'perfil.sobreMiEjemplo': 'E.g. I laugh at everything, I cook better than I dance, and I never say no to a coffee.',
    'perfil.tuTelefono': 'Your phone',
    'perfil.pais': 'Country',
    'perfil.seleccionaPais': 'Pick your country',
    'perfil.buscarPais': 'Search country or code...',
    'perfil.minimo': 'Minimum',
    'perfil.maximo': 'Maximum',
    'perfil.guardarCambios': 'Save changes',
    'perfil.eliminarCuenta': 'Delete account',
    'perfil.cerrarSesion': 'Sign out',
    'perfil.correoSub': 'Send us a message',
    'perfil.whatsappSub': 'Chat with us',
    'perfil.tuCorreo': 'Your email',
    'perfil.mensajeEnviado': 'Message sent!',
    'perfil.notifSubtitulo': 'Choose what you want to get',
    'perfil.sesionCerrada': 'Your session ended. Sign in again to see your profile and confirm your spot.',
    'perfil.sesionCerradaHint': "You're viewing Nospi inside another app (WhatsApp, for example). Open it in Safari, Chrome or the Nospi app to sign in.",
    'perfil.contrasenaSubtitulo': 'Enter your current password and the new one',
    'perfil.contrasenaActual': 'Current password *',
    'perfil.contrasenaActualPh': 'Current password',
    'perfil.contrasenaNueva': 'New password *',
    'perfil.contrasenaNuevaPh': 'New password (at least 6 characters)',
    'perfil.contrasenaConfirmar': 'Confirm new password *',
    'perfil.contrasenaConfirmarPh': 'Confirm the new password',

    // ---------- Selector de idioma ----------
    'idioma.titulo': 'Language',
    'idioma.espanol': 'Español',
    'idioma.ingles': 'English',
  },
};
